### PR TITLE
Improvement about llama.cpp and a little about chat

### PR DESCRIPTION
**Pull request by Foxtr0t1337**
### modules/llamacpp_model.py #3106 
llama_cpp lib has some known issues which will cause some tokens fail to decode without any error (hard to spot but impact the outcome).
After tweaking the generate function you can avoid those issues.

Update: 
I don't know whether it is intended or something. But it seems that llamacpp_model.py:generate() didn't use the value 'truncation_length'. 
It seems that it is causing model to stop generating when the context limit is reached.
So I added the 'truncation_length' support. It seems working just fine!

### server.py
This is about chat mode.
The radio 'mode' is set to 'instruct' by default.
This will cause some issues when you change the character.
Before the fix, it won't load the persistent history normally, and won't show the greeting.
There is seemingly no way to load history besides set mode to chat/chat-instruct and load None then load the character or download and upload the history(currently it seems that you can't download the persistent history).
This patch will automatically change the radio to 'chat' if it is not 'chat' or 'chat-instruct' when you select a character.
So that the history and greeting will load normally.

### modules/shared.py
Set user name to 'You' is not good.
It makes characters confuse.
They are going to assume that the pronoun 'You' is the user 'You'.
e.x.
```
<user>: You are an AI!
<bot>: Wow! How do you feel when you know that?
```
It is obvious that 'You' is a confusing name.
I changed it to 'User' for disambiguation.

My personal comment:
Chat mode is my favorite feature and I'd love to improve it.

### CODE REVIEW

**Comment by Ph0rk0z** [comment]
You should change 1 thing at a time per PR probably. I don't really do a lot of llama cpp so I can't tell if that fix is good or not.. 

The "you" is left over from pygmalion which used that format. I agree that it has confused some newer models and encouraged them to reply as me, etc.

**Comment by Foxtr0t1337** [comment]
> You should change 1 thing at a time per PR probably. I don't really do a lot of llama cpp so I can't tell if that fix is good or not..
> 
> The "you" is left over from pygmalion which used that format. I agree that it has confused some newer models and encouraged them to reply as me, etc.

Thanks for you suggestion! I forgot I was using the main branch so lol.
On this PR I will only work on that llama.cpp afterwards.

**Comment by oobabooga** [comment]
@Foxtr0t1337 I like that you solved the unicode character and truncation problems in one go. The issue with replacing `create_completion` with `generate` is that `create_completion` implements a cache logic initialized with

```
model.set_cache(LlamaCache(capacity_bytes=cache_capacity))
```

that does not get used without in `generate`. See the source [here](https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama.py#L872).

Is there a way to make unicode work while maintaining this function call?

**Comment by Foxtr0t1337** [comment]
> @Foxtr0t1337 I like that you solved the unicode character and truncation problems in one go. The issue with replacing `create_completion` with `generate` is that `create_completion` implements a cache logic initialized with
> 
> ```
> model.set_cache(LlamaCache(capacity_bytes=cache_capacity))
> ```
> 
> that does not get used without in `generate`. See the source [here](https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama.py#L872).
> 
> Is there a way to make unicode work while maintaining this function call?

@oobabooga 

Sorry for the inconvenience. I didn't see that there is a cache problem before you point it out.
I was still wondering why is my fix so slow.
So thanks for that.

I don't think that you can make it work because the decoding is inside the `create_completion` function.
However maybe I can check the code you pointed out and fix the cache problem.

**Comment by Foxtr0t1337** [comment]
Updating the `llama-cpp-python` package will solve the decoding problem.
When updating that we can solve the truncation problem.

**Comment by oobabooga** [comment]
Thanks for the heads up, I will update to the latest version today.

**Pull request closed without merging**
