### PR TITLE
Move one-click-installers into the repository

### PR DESCRIPTION
**Pull request by oobabooga**
The idea of this PR is to move https://github.com/oobabooga/one-click-installers into the repository.

The motivations are:

1) Making the installers self-update when the `update` scripts are executed. Currently there are many people running 6 months old versions of the installers, and when the installation breaks because of that, they have no way of knowing that their files are not up-to-date.
2) Increasing the attention to the installers, in particular from AMD/Intel Arc/Mac Metal users, such that we can eventually reach easy and stable installation on any GPU.

Once merged, a check for `Path('../webui.py').exists()` can be added, and users can be warned about the possibility of deleting their existing `ìnstaller_files` folder and running the moved `start` scripts to reinstall the requirements without losing their models or data.

There are some things to fix, ~in particular lines 120 and 234 of webui.py (marked with a TODO comment)~, and possibly other things that I haven't noticed.

@jllllll does this make sense to you?

### CODE REVIEW

**Comment by jllllll** [comment]
Yes, this makes sense. I have thought about this before. It seems to be the most sensible way to allow the installer itself to be updated. I've seen tons of instances of people using outdated versions of it and even quite a few instances of people believing that the installer's update script was also updating the installer.

The only thing that I was unsure of is how to incorporate installation of some of the more basic requirements, such as the installation of Git, to ensure that installer functionality is not reduced by this transition. I tried to find a way to reliably create a local git repository in a non-empty directory to allow for updates to the installer's files, but I've run into a lot of issues with this as Git simply isn't designed for such a thing. It can be done, just not reliably. It is possible that this transition will make this strategy more viable, but I need to do some more testing.

Worst case scenario, users will just have to install Git themselves as everything else can be handled by the installer after cloning.
My hope is that users can download the repo's [zip archive](https://github.com/oobabooga/text-generation-webui/archive/refs/heads/main.zip) and then the installer can add the git history for later `git pull` commands to function. Essentially, recreate a `git clone` without the need for having Git installed beforehand.

**Comment by jllllll** [comment]
This is what I have so far:
```
git init
git remote add origin https://github.com/oobabooga/text-generation-webui
git fetch
git remote set-head origin -a
git reset origin/HEAD
git branch --set-upstream-to=origin/HEAD
```
These commands would take place after the Conda env is set up and if the `.git` directory is missing.

**Comment by oobabooga** [comment]
I wasn't even considering that `.git` would not be in the .zip, well noted. I'll do some testing in the next days to see where else the moved installer could go wrong; meanwhile, if you want to PR the commands that you have found so far to this branch to be properly acknowledged, please feel free to.

**Comment by oobabooga** [comment]
I just merged the two repos in this branch and brought every commit in. Then I can create a merge commit (without squashing) so that the commits will remain.

**Comment by jllllll** [comment]
Made a PR here: #4029

---
I think the WSL installer is going to need somewhat of a rewrite to account for the new change.
Not sure how I'm going to approach it yet. I'll either write some code to compensate for the change and maintain past functionality (clone the webui into WSL env as before) or I'll rewrite it to rely on `start_linux.sh` for most of it's functionality.

**Comment by jllllll** [comment]
Probably isn't necessary. In the past, it was useful to install as not everything was pre-compiled for CUDA. Namely, llama-cpp-python. That isn't the case anymore. Those that want to compile things should be able to enter the simple command for installing the Toolkit.

ExLlamaV2 only needs it for now. Eventually turboderp intends to provide pre-compiled kernel wheels via pypi.
Already have the code done for that in a fork in case it is needed: https://github.com/jllllll/exllamav2
Haven't decided yet if I should go ahead and make the wheels.

**Comment by oobabooga** [comment]
ExLlamaV2 is quite experimental still. I think it's fine to wait for turboderp to make his own wheels when things get more figured out.

bitsandbytes and `load_in_4bit` are working fine on a fresh install.

**Comment by oobabooga** [comment]
Here is one more feature: allowing the start scripts to have command-line flags like `./start_linux.sh --listen`. I haven't tested the Windows and WSL ones.

**Comment by jllllll** [comment]
I'll test those real quick. If it works, then there definitely isn't a need for the env var.

**Comment by jllllll** [comment]
`start_wsl.bat` needs to use `%*`. Other than that, both work barring some minor bugs with CMD I encountered that required restarting CMD in order to not stack args and crash the script somehow.

I noticed an issue during my testing with one of the changes in my PR to the Windows scripts. I constantly forget that CMD uses `nul` instead of `null`. Can you change this line in `cmd/start/update_windows.bat`:
```
(conda deactivate && conda deactivate && conda deactivate) 2>null
```
To:
```
(conda deactivate && conda deactivate && conda deactivate) 2>nul
```

**Comment by oobabooga** [comment]
Good to know that it worked. I have made those fixes here: https://github.com/oobabooga/text-generation-webui/pull/4028/commits/c74326de023a5f5b4005684a05cd87116efce8bc

**Comment by oobabooga** [comment]
I have added migration instructions here: https://github.com/oobabooga/text-generation-webui/wiki/Migrating-an-old-one%E2%80%90click-install

@jllllll is there anything else that you think needs testing?

**Comment by jllllll** [comment]
Only thing that I can think of is that it might be useful to detect an update to the installer somehow and have the user restart it after a git pull. That can come later though as I still have to work out if that is even feasible.

**Comment by oobabooga** [comment]
It should be possible to compare the hashes for the installer files before and after the update using something similar to this:

```python
if p.exists():
    with open(p, "rb") as f:
        bytes = f.read()

    file_hash = hashlib.sha256(bytes).hexdigest()
```

I agree that this can indeed be done later.

Thank you so very much for your help with this PR!!

**Comment by oobabooga** [comment]
I though I was safe with bitsandbytes but I got this error on my laptop with a GTX 1650 (Linux):

```
===================================BUG REPORT===================================
/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /text-generation-webui/installer_files/env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('local/AcerNitro5'), PosixPath('@/tmp/.ICE-unix/1550,unix/AcerNitro5')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-cinnamon')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/cinnamon.mandatory.path')}
The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/bc22d900_ee83_4807_9d96_b57c22fe8768')}
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/cinnamon.default.path')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

```

It works fine on my computer with a RTX 3090. I'm looking for a solution... It can't be that `nvcc` is necessary for bitsandbytes.

**Comment by oobabooga** [comment]
I though I was safe with bitsandbytes but I got this error on my laptop with a GTX 1650 (Linux):

```
===================================BUG REPORT===================================
/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /text-generation-webui/installer_files/env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-cinnamon')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/cinnamon.mandatory.path')}
The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/bc22d900_ee83_4807_9d96_b57c22fe8768')}
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/cinnamon.default.path')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

```

It works fine on my computer with a RTX 3090. I'm looking for a solution... It can't be that `nvcc` is necessary for bitsandbytes.

**Comment by jllllll** [comment]
@oobabooga 
It doesn't need NVCC, but it does need the CUDA runtime lib. `libcudart.so` in the case of Linux.
For the Windows fork, I added code to find and load the lib included with torch.
No clue why Tim Dettmers didn't already have that considering that he intended to rely on it in the more recent versions.
If needed, I can make a fork of the Linux version to add that code.

An alternative to installing the entire Toolkit is to just get the libs with:
```
conda install cuda-cudart-dev -c nvidia/label/cuda-11.7.1
```

---
I haven't tested it myself yet, but I suspect that the commit you linked is excluding Linux from installing the CUDA 11.7 Pytorch.
The easiest solution would be to just use this for the NVIDIA installation command:
```py
run_cmd('conda install -y -k cuda-cudart-dev ninja git -c nvidia/label/cuda-11.7.1 && python -m pip install torch==2.0.1+cu117 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117', assert_success=True, environment=True)
```

**Comment by oobabooga** [comment]
@jllllll I think that the question is that 

`--index-url https://download.pytorch.org/whl/cu117`

is not defined on Linux somehow. The [Pytorch website](https://pytorch.org/get-started/locally/) recommends this command for 11.7 on Linux:

```
pip3 install torch torchvision torchaudio
```

And this one for 11.8 on Linux:

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

Meanwhile, for 11.7 on Windows the command is

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
```

No idea why, but the last command above doesn't work on Linux, but the recommended one works on both my machines.

**Comment by jllllll** [comment]
They must have changed their packaging formats. I'll check their repos and see what's going on.

**Comment by jllllll** [comment]
Not sure what they changed or why. They may be in the middle of a transition to the manylinux standard and decided to put the CUDA wheels on pypi? These are the SHA256 hashes of their wheels:
- https://download.pytorch.org/whl/cu117/torch-2.0.1%2Bcu117-cp310-cp310-linux_x86_64.whl
  - `BB54B705185BEA820E6EC6485A25761BC03F689E1A09A37D814D6EA8E276B5BD`
  - 1.7 GB
- https://download.pytorch.org/whl/cpu/torch-2.0.1%2Bcpu-cp310-cp310-linux_x86_64.whl
  - `FEC257249BA014C68629A1994B0C6E7356E20E1AFC77A87B9941A40E5095285D`
  - 186 MB
- [pypi](https://pypi.org/project/torch/#copy-hash-modal-bfe6a319-e70f-46da-b5a3-183d0f433b02)
  - `8CED00B3BA471856B993822508F77C98F48A458623596A4C43136158781E306A`
  - 619.9 MB

**Comment by byungyoonc** [comment]
I don't know from when but now torch defaults to CUDA 12.1 instead of 11.7 if the version is not specified, resulting in the error unable to find the file libcudart.so.11.0.

By matching the command to the one for Windows and additionally installing cudatoolkit after running ./start_linux.sh for the first time solved the problem.

**Pull request merged**
