### PR TITLE
Sending peft back to original (issue with kwargs in PeftConfig) and lora.py changes

### PR DESCRIPTION
**Pull request by FartyPants**
see peft_model.py line 169, # load the config, the new repo passes kwargs to PeftConfig that will break ooba
PeftConfig doesn't want 'dtype' and 'device_map'
1. check if newer peft fixes it
2. the main should stay on old peft untill this is fixed otherwise loading LORA doesn't work

### CODE REVIEW

**Comment by FartyPants** [comment]
https://github.com/oobabooga/text-generation-webui/issues/2623

**Comment by ashleykleynhans** [comment]
Doesn't work for me on Linux, still getting an error:

```
INFO:Applying the following LoRAs to PygmalionAI_pygmalion-6b: snappic
Traceback (most recent call last):
  File "/workspace/text-generation-webui/server.py", line 1081, in <module>
    add_lora_to_model(shared.args.lora)
  File "/workspace/text-generation-webui/modules/LoRA.py", line 80, in add_lora_to_model
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_names[0]}"),adapter_name=lora_names[0], **params)
  File "/workspace/venv/lib/python3.10/site-packages/peft/peft_model.py", line 169, in from_pretrained
    PeftConfig.from_pretrained(model_id, subfolder=kwargs.get("subfolder", None), **kwargs).peft_type
  File "/workspace/venv/lib/python3.10/site-packages/peft/utils/config.py", line 114, in from_pretrained
    config = cls(**kwargs)
TypeError: PeftConfig.__init__() got an unexpected keyword argument 'dtype'
```

**Comment by oobabooga** [comment]
What command are you using exactly @FartyPants and @ashleykleynhans? Is this monkeypatch + gptq-for-llama, 16bit, autogptq?

**Comment by ashleykleynhans** [comment]
Never mind, my bad, I deleted my venv and recreated it and can confirm that this fix resolves the issue, thank you, nice work!

**Comment by ashleykleynhans** [comment]
> What command are you using exactly @FartyPants and @ashleykleynhans? Is this monkeypatch + gptq-for-llama, 16bit, autogptq?

It happens when applying a LoRA, and also when using the `--lora` command line argument at startup to use a LoRA, but this PR fixes it.

**Comment by FartyPants** [comment]
> What command are you using exactly @FartyPants and @ashleykleynhans? Is this monkeypatch + gptq-for-llama, 16bit, autogptq?

This is when you apply lora, the perf commit you put in the requirements added kwargs 
line 169 # load the config
config = PEFT_TYPE_TO_CONFIG_MAPPING[
PeftConfig.from_pretrained(model_id, subfolder=kwargs.get("subfolder", None), **kwargs).peft_type
].from_pretrained(model_id, subfolder=kwargs.get("subfolder", None), **kwargs)

but if the kwargs have 'device_map' or 'dtype' then it will blow in the construct of config.py
line 114: config = cls(**kwargs)
TypeError: PeftConfig.init() got an unexpected keyword argument 'device_map'

but at the same time PERF actually expecting kwargs in from_pretrained to have 'device_map', in load_adapter perf_model.py is expecting it to have it.

This isn't necessary bug in ooba, it's a bug in perf, but for now you need to go back to the original PERF version you had.
I opened issue in perf. It's something they never tested I assume.

**Comment by FartyPants** [comment]
Got back info from PEFT people, this is fixed in:
https://github.com/huggingface/peft/pull/561

**Comment by oobabooga** [comment]
Thanks for the update @FartyPants

**Comment by younesbelkada** [comment]
Should be fixed in https://github.com/huggingface/peft/pull/575

**Comment by Nixellion** [comment]
But not yet fixed in webui, right?

**Comment by oobabooga** [comment]
Should be fixed now https://github.com/oobabooga/text-generation-webui/commit/490a1795f090fda59934224919013f86914b2c1b

**Comment by 93041025** [comment]
I'm still encountering an error. I ran "update_wsl" and started with "start_wsl". When the model is loaded onto the CPU, it works fine. However, I'm still experiencing issues when loading it onto the GPU.

**Pull request closed without merging**
