### PR TITLE
Update download-model.py (Allow single file download)

### LINKED ISSUE #3717: Download only one model when multiple are available in the Hugging Face repo
I'm encountering an issue while attempting to utilize this file: https://huggingface.co/TheBloke/WizardCoder-Python-13B-V1.0-GGUF/blob/main/wizardcoder-python-13b-v1.0.Q5_K_M.gguf

When I input "TheBloke/WizardCoder-Python-13B-V1.0-GGUF" into the model download section of the webui it triggers the download of all available model versions, rather than just the specific one I intend to use. This leads to an unnecessary downloads and wasted space.

Is there a way to prevent this and only download the required model version to save on download size?

### PR DESCRIPTION
**Pull request by bet0x**
## Checklist:

- [ X] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

With this change, we can download a single file, and this should fix #3717 and not download the entire repo:

```
bet0x@dell:~/text-generation-webui$ python download-model.py TheBloke/Griffin-3B-GGML --specific-bin=griffin-3b.ggmlv3.q4_0.bin
Downloading griffin-3b.ggmlv3.q4_0.bin to models/TheBloke_Griffin-3B-GGML
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.93G /1.93G  4.15MiB/s
bet0x@dell:~/text-generation-webui$ ll models/TheBloke_Griffin-3B-GGML/
total 1883252
drwxrwxr-x 2 bet0x bet0x       4096 Aug 28 13:36 ./
drwxrwxr-x 4 bet0x bet0x       4096 Aug 28 13:36 ../
-rw-rw-r-- 1 bet0x bet0x 1928429856 Aug 28 13:43 griffin-3b.ggmlv3.q4_0.bin
-rw-rw-r-- 1 bet0x bet0x        208 Aug 28 13:36 huggingface-metadata.txt
bet0x@dell:~/text-generation-webui$
```

### CODE REVIEW

**Comment by oobabooga** [comment]
This in combination with https://github.com/oobabooga/text-generation-webui/pull/3737 is a great improvement. 

For this PR I would like just 1 change: could you make it such that GGUF/GGML files are saved directly into models/ instead of a subfolder of models/?

**Comment by bet0x** [comment]
> 

Yes. I will submit the change soon.

**Comment by bet0x** [comment]
@oobabooga I implemented your suggestion.

**Comment by oobabooga** [comment]
Thank you @bet0x. I have made some simplifications and renamed the parameter to `--specific-file`. It should be all good now.

**Comment by bet0x** [comment]
> Thank you @bet0x. I have made some simplifications and renamed the parameter to `--specific-file`. It should be all good now.

Excellent @oobabooga. I like these updates a lot more, simple and effective.

**Pull request merged**
