### PR TITLE
Dropdown item fixes

### PR DESCRIPTION
**Pull request by missionfloyd**
## Checklist:
- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

Removes excess whitespace (except on mobile for touchscreens) and displays long items without wrapping.

Particularly effective on the models dropdown, which tends to be long and narrow at lower resolutions.

Before:
image

After:
image

### CODE REVIEW

**Comment by bet0x** [comment]
@missionfloyd I've been racking my brain trying to implement something similar on the other panel. I wanted to add a dropdown after clicking on the 'Get file list' and fill the "File name" Textbox, but I don't know if it's possible

**Comment by missionfloyd** [comment]
The textbox could just be replaced with a dropdown, populated by "get file list" and cleared when the repo textbox is changed. This could also allow specifying multiple files.

**Comment by FartyPants** [comment]
excellent

**Comment by oobabooga** [comment]
This is a valid change, but for a matter of arbitrary personal taste I prefer to keep the current appeareance as I find it more readable.

**Pull request closed without merging**
