### PR TITLE
Jinja instruct templates

### PR DESCRIPTION
**Pull request by oobabooga**
Status: kind of works.

Based on https://huggingface.co/docs/transformers/main/chat_templating

### CODE REVIEW

**Comment by Ph0rk0z** [comment]
We won't have to eat their "Assistant is helpful and harmless" system messages from this, will we?

**Comment by Tostino** [comment]
@oobabooga Just FYI, I have implemented this for vLLM's OpenAI api: https://github.com/vllm-project/vllm/pull/1365

Was pretty straight forward.

@Ph0rk0z no...those are just examples. The template itself will determine what the template does. Some models may have a hard coded system message in their template, others will allow a configurable system message. Just depends.

**Comment by Dampfinchen** [comment]
GGUF now supports Instruct templates.

**Comment by oobabooga** [comment]
Moved to https://github.com/oobabooga/text-generation-webui/pull/4874

**Pull request closed without merging**
