### PR TITLE
SileroTTS preview

### PR DESCRIPTION
**Pull request by missionfloyd**
With so many voices and no meaningful names for them, I thought it'd be useful to have a way to preview them.

Adds a preview button and text field. If nothing is entered, it reads a random [Harvard sentence](http://www.cs.columbia.edu/~hgs/audio/harvard.html).

https://user-images.githubusercontent.com/4073789/236999932-b1892264-ff06-4bfc-9ccb-77730a6c642c.mp4

### CODE REVIEW

**Comment by oobabooga** [comment]
You can find samples for all voices here https://oobabooga.github.io/silero-samples/index.html

**Comment by missionfloyd** [comment]
Wow, that was fast.

**Comment by missionfloyd** [comment]
Wouldn't it be better to preview the voices right in the UI, and with the selected speed and pitch settings? There aren't even any links to that page anywhere.

**Comment by oobabooga** [comment]
You are right, it doesn't hurt to have a preview.

**Comment by missionfloyd** [comment]
c35860ff2fee36603ba10d95522ae3212ed4be4d

@oobabooga Is there a problem with it? What changed?

**Pull request merged**
