### PR TITLE
Add support for ExLlama_HF in Jetson Dockerfile

### PR DESCRIPTION
**Pull request by toolboc**
## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by darkacorn** [comment]
exllama_hf is in ooba and the dockerfile is somewhat specific to jetson ?

**Comment by toolboc** [comment]
@darkacorn, this Dockerfile is specific to running on NVIDIA Jetson Embedded hardware and provides the exllama repo into the repositories folder which allows for ExLlama_HF ready-to-go in this image (this is not present in default ooba).

**Comment by darkacorn** [comment]
that is exactly my point nothing in the PR name specifies that

**Comment by oobabooga** [comment]
I can't test this and I don't use Docker. I suggest submitting it to https://github.com/Atinoda/text-generation-webui-docker.

**Pull request closed without merging**
