### PR TITLE
Falcon support

### PR DESCRIPTION
**Pull request by Honkware**
- Include 'einops' in requirements for Falcon support
- Append Falcon details to README regarding 'trust-remote-code'
- Implement 'trust-remote-code' option in UI
- Integrate Falcon configuration

### CODE REVIEW

**Comment by yhyu13** [comment]
@oobabooga Yes, this pr would allow us to review a potential SOTA open source model so far.
@TheBloke Is the change here suffice to run the GPTQ version of falcon?

**Comment by TheBloke** [comment]
Yeah it is. I didn't see this PR already existed and did another here for the `trust_remote_code` issue:  https://github.com/oobabooga/text-generation-webui/pull/2374

This one is better as it adds einops as well so I will close mine and this should be used instead.  

I've put out one model already that will work with this or my PR: https://huggingface.co/TheBloke/falcon-7b-instruct-GPTQ

And am working on the 40B now

**Comment by D-Ogi** [comment]
How to get this to work? In `config-user.json` I added `trust_remote_code: true` to relevant section. I compiled the recent AutoGTPQ within "cmd_windows.bat" environment. Installed dependencies from this PR's requirements.txt.  Also I added `"trust_remote_code": true` to config.json for a Falcon 7B's model. I ticked the box in UI on Models tab.

Tried saving, loading, reloading, restarting ooba many times and as the result, all I get is the following error message:
`File “C:\[..]\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py”, line 934, in from_pretrained raise ValueError( ValueError: Loading models\TheBloke_falcon-7b-instruct-GPTQ requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error.`
and
`WARNING:The AutoGPTQ params are: {'model_basename': 'gptq_model-4bit-64g', 'device': 'cuda:0', 'use_triton': False, 'use_safetensors': True, 'max_memory': None}`

**Comment by TheBloke** [comment]
That's odd, @D-Ogi . silly question but you definitely pulled this PR?  Can you show the contents of the file `text-generation-webui/modules/AutoGPTQ_loader.py` ?

If you passed --trust-remote-code on the command line then that should be all that's required to launch AutoGPTQ with the right settings. So I'm wondering if your `AutoGPTQ_loader.py` is not updated for some reason.

**Comment by D-Ogi** [comment]
@TheBloke this PR seems not to include any changes in `AutoGPTQ_loader.py`. Your's does however.

**Comment by TheBloke** [comment]
Oh shit! I didn't spot that.  I saw he implemented in the UI and just assumed it put it in AutoGPTQ_Loader.py as well as that's required

Well then for now, I suggest manually making the change in my PR to your local file.  

@Honkware can you incorporate the change to AutoGPTQ_loader.py from my closed PR: https://github.com/oobabooga/text-generation-webui/pull/2374/commits/473a57e35219c063d2fc230cfc7b5a118b448b38

**Comment by D-Ogi** [comment]
I herby confirm that merging your PR fixed the issue! <3 

Unfortunately that also means that this PR is not working as intended and UI arguments are not passed to the loader.

Btw. I would suggest you to consider replacing `pip install .` with `pip install .[llama]` in your AutoGPTQ guide.

**Comment by TheBloke** [comment]
Why `pip install .[llama]` ? I thought that's only for people using old versions of transformers, pre-Llama?

**Comment by TheBloke** [comment]
Thanks Honkware, that was quick! :)

**Comment by oobabooga** [comment]
Thank you. I have

1) Removed the settings from models/config.yaml: falcon is not always an instruct model; auto-enabling trust_remote_code for models with falcon in their name can be abused; auto-devices doesn't always apply to falcon.

2) Added an AutoGPTQ checkbox to the UI

3) Added descriptions for the new checkboxes

**Comment by TheBloke** [comment]
Thanks so much ooba and Honkware

**Pull request merged**
