### PR TITLE
Add ability to load a character via args

### PR DESCRIPTION
**Pull request by bmoconno**
* Add new `--character` argument to `server.py` to load a selected default character
* Also make character choice persistent, so on refresh the last chosen character will still be selected.

This PR is fulfilling the requested enhancement in #542, and adds the ability to load a character by including the filename of a character in the `characters` directory (with or without extension).

Example: `python server.py --chat --character test`

### CODE REVIEW

**Comment by Malrama** [comment]
May I suggest having this as a setting in settigs.json instead of a starting argument?
What way we could even use 	use something like this, as we do with Presets:
```
//file settings.json
[...]
"characters": {
		"default": "Default"
                ".*alpaca": "Alpaca"
                ".*vicuna": "Vicuna"
}
[...]
```
That way we won't bring in unnecessary stating arguments and cleanly separate model specific running parameters (e.g. preset, character, parameters) and model loading starting arguments, which later are essential for loading a model.

I hope my suggestion makes sense.

Thank you

**Comment by bmoconno** [comment]
@Malrama 

I think maybe having both would be the way to go? That way it can support either method and people can choose whichever they prefer, or even use both (giving priority to the `--character` argument if it is used)?

I'll see if I can get this suggestion implemented today or tomorrow.

**Comment by Malrama** [comment]
> @Malrama
> 
> I think maybe having both would be the way to go? That way it can support either method and people can choose whichever they prefer, or even use both (giving priority to the `--character` argument if it is used)?
> 
> I'll see if I can get this suggestion implemented today or tomorrow.

I am really not a fan of having model running parameters in the starting arguments. I do think that the settings.json file is the perfect place for that and it will only make starting arguments unnecessary bloated.

Ofc adding both would be an option. But I suggest, in my humble opinion, to just add the .json config support. I don't see the benefit in adding it as a starting argument. It would also introduce running parameters into the starting arguments, which are currently separated nicely. (User-friendliness)

Greeting

**Comment by bmoconno** [comment]
Closing this PR to break into smaller parts that might get merged.

**Pull request closed without merging**
