### PR TITLE
fix: instruction_template not applying from user_settings

### PR DESCRIPTION
**Pull request by hronoas**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by oobabooga** [comment]
Instruction templates are not set by name anymore. They are set by value in settings.yaml

The idea is to have the templates in the model metadata, and in models/config.yaml otherwise.

**Comment by FartyPants** [comment]
We could add button that would write the jinja script to the metadata if it is not already there. Once people start including the template in the metadata, all the problems would be solved.

**Comment by hronoas** [comment]
How to use and save custom template for gguf in this case?
Settings.yaml - used globally, I would like to use an individual custom template for each model.
There are models in which a start prompt is prescribed. I prefer not to change the template manually every time.

**Comment by oobabooga** [comment]
If the template is included in the GGUF metadata, it should be automatically set after https://github.com/oobabooga/text-generation-webui/pull/4975

Otherwise, the best option is to add a regex pattern to models/config.yaml or models/config-user.yaml (look at models/config.yaml for examples).

**Comment by hronoas** [comment]
> Otherwise, the best option is to add a regex pattern to models/config.yaml or models/config-user.yaml (look at models/config.yaml for examples).

The fact of the matter is that when you specify instruction template in models/config-user.yaml, the template is not loaded. This commit is precisely about the fact that config-user.yaml is loaded later than instruction_template_str is created

**Comment by hronoas** [comment]
изображение

**Comment by oobabooga** [comment]
instruction template is model metadata, not an user setting.

**Pull request closed without merging**
