### PR TITLE
Use current input for Impersonate (continue impersonate feature)

### PR DESCRIPTION
**Pull request by kamyker**
Makes Impersonate use current input instead of replacing it.

Also changed the space to be inserted after generation attempts. Not sure what was the purpose in doing it before them.

### CODE REVIEW

**Comment by kamyker** [comment]
merged with recent changes

**Review by mcmonkey4eva — APPROVED** [review]
This will need to be rebased/merged onto main before it can be pulled -- but I tested and it's working exactly as intended, and is definitely a nice feature to have.

**Comment by kamyker** [comment]
> This will need to be rebased/merged onto main before it can be pulled -- but I tested and it's working exactly as intended, and is definitely a nice feature to have.

I prob resolved it using github gui

**Comment by kamyker** [comment]
well, not anymore

**Pull request merged**
