### PR TITLE
Fix issue #3822 and #3839

### PR DESCRIPTION
**Pull request by Touch-Night**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by missionfloyd** [comment]
https://docs.python.org/3/library/html.html#html.unescape

**Comment by Touch-Night** [comment]
Oops, I'm not aware of that

**Comment by oobabooga** [comment]
The branch in this PR is protected and I can't edit it.

**Comment by Touch-Night** [comment]
> The branch in this PR is protected and I can't edit it.

I have disabled it just now.

**Comment by oobabooga** [comment]
Thanks. I have escaped back the Google Translate output (after unescaping it for the translation) and removed the changes to extensions.py as it can probably be made in a simpler way by removing inactive extensions from the `state` variable (or setting things to False). Feel free to submit a new PR if you can manage to get that working.

**Comment by Touch-Night** [comment]
> Thanks. I have escaped back the Google Translate output (after unescaping it for the translation) and removed the changes to extensions.py as it can probably be made in a simpler way by removing inactive extensions from the variable (or setting things to False). Feel free to submit a new PR if you can manage to get that working.`state`

I have tried some ways before I decide to fix it this way, which is not really disabling extensions. The way you used to load an extension is directly import them, which cannot be really deleted unless a complete restart. I have noticed that there is a state value for each extensions, and have tried to use `del loaded_extension.script` and `state.pop(extension_name_if_state[name][0])`, but it always failed to load extensions which are unloaded before the auto restart, and keep getting `Attribute error: extension_name has no attribute script` when running `get_attr(extensions, name).script` even if it is right below `exec(f"import extensions.{name}.script")`. Maybe the simpler way you mentioned does not exist.

**Comment by oobabooga** [comment]
Yes, unimporting the python module will not work. The best that can be done is remove the disabled extensions from the `iterator()`.

**Comment by Touch-Night** [comment]
> Yes, unimporting the python module will not work. The best that can be done is remove the disabled extensions from the `iterator()`.

Done in #3965

**Pull request merged**
