### PR TITLE
Bump bitsandbytes Windows wheel to 0.40.0.post4

### PR DESCRIPTION
**Pull request by jllllll**
https://github.com/TimDettmers/bitsandbytes/compare/b8da4a165a9f181c3d10bf6e751589270f0c92ff...817bdf632529329bb5ba73260e8bdbe22bb9e9d2

### CODE REVIEW

**Comment by Malrama** [comment]
Bitsandbytes is not showing me this message at the beginning of every API call since upgrade to post4

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\XXX\Desktop\TextGPT\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
CUDA SETUP: CUDA runtime path found: C:\Users\XXX\Desktop\TextGPT\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\XXX\Desktop\TextGPT\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
```

You guys have any idea why? It doesn't happen in TextGen itself. Just in every API call, no matter if freshly started or already done some calls in that run.

**Comment by jllllll** [comment]
@Malrama The webui was setting the `BITSANDBYTES_NOWELCOME` env var before to hide that message. Is it not anymore?
Personally, I prefer having that message as it makes debugging much easier.

**Comment by jllllll** [comment]
The env var is still being set. I'll go over the bnb changes to see why it might be getting ignored.

**Comment by jllllll** [comment]
@Malrama There haven't been any changes to the code involved with that message. Not sure why it would suddenly start appearing again, unless the API code is overriding the env var somehow.

**Comment by Malrama** [comment]
@jllllll I just double checked and I am so sorry. I made a little upsi.

It wasn't TextGen that was giving me this message but code in the HugginFaceEmbedding (which I use with the API calls). So it's not related to TextGen, but the all-MiniLM-L6-v2 embedding.

Sorry about that. Do you have the env var by hand by any chance? So that I can add it so my code? ^^ I don't even understand why bnb would send this message every time it runs ...

**Comment by jllllll** [comment]
```python
os.environ['BITSANDBYTES_NOWELCOME'] = '1'
```

**Comment by Malrama** [comment]
Thank you very much. Now everything is good again. Sorry for the false alarm ^^

**Pull request merged**
