### PR TITLE
Add LoRA support

### PR DESCRIPTION
**Pull request by oobabooga**
Based on https://github.com/tloen/alpaca-lora/

Probably not the best way to do it. WIP. Suggestions are welcome.

## Instructions
1. Re-install the requirements

```
pip install -r requirements.txt
```

2. Download the LoRA

```
python download-model.py tloen/alpaca-lora-7b
```

3. Load llama-7b in 8-bit mode (it only seems to work in 8-bit mode, don't ask me why)

```
python server.py --model llama-7b --load-in-8bit
```

4. Select the LoRA in the Parameters tab.

## Prompt
For this particular LoRA, apparently the prompt must be formatted like this:

```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Write a Python script that generates text using the transformers library.
### Response:
```

Sample output:

```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Write a Python script that generates text using the transformers library.
### Response:

import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModelForCausalLM.from_pretrained("bert-base-uncased")
texts = ["Hello world", "How are you"]
for sentence in texts:
sentence = tokenizer(sentence)
print(f"Generated {len(sentence)} tokens from '{sentence}'")
output = model(sentences=sentence).predict()
print(f"Predicted {len(output)} tokens for '{sentence}':\n{output}")
```

### CODE REVIEW

**Comment by bartman081523** [comment]
I have the following error: Also I updated peft, but the problem was not with peft.

```
python server.py --model llama-7b-hf  --lora alpaca --auto-devices --listen --cai-chat --gptq-bits 4

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /opt/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/user/Downloads/Python/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Loading llama-7b-hf...
Loading model ...
Done.
Loaded the model in 6.67 seconds.
alpaca
Adding the LoRA alpaca to the model...
Traceback (most recent call last):
  File "/home/user/Downloads/Python/text-generation-webui/server.py", line 240, in <module>
    add_lora_to_model(shared.lora_name)
  File "/home/user/Downloads/Python/text-generation-webui/modules/LoRA.py", line 18, in add_lora_to_model
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"loras/{lora_name}"))
  File "/home/user/Downloads/Python/text-generation-webui/venv/lib/python3.10/site-packages/peft/peft_model.py", line 143, in from_pretrained
    model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config)
  File "/home/user/Downloads/Python/text-generation-webui/venv/lib/python3.10/site-packages/peft/peft_model.py", line 514, in __init__
    super().__init__(model, peft_config)
  File "/home/user/Downloads/Python/text-generation-webui/venv/lib/python3.10/site-packages/peft/peft_model.py", line 79, in __init__
    self.base_model = LoraModel(peft_config, model)
  File "/home/user/Downloads/Python/text-generation-webui/venv/lib/python3.10/site-packages/peft/tuners/lora.py", line 118, in __init__
    self._find_and_replace()
  File "/home/user/Downloads/Python/text-generation-webui/venv/lib/python3.10/site-packages/peft/tuners/lora.py", line 181, in _find_and_replace
    self._replace_module(parent, target_name, new_module, target)
UnboundLocalError: local variable 'new_module' referenced before assignment

```

**Comment by oobabooga** [comment]
Apparently it doesn't work with GPTQ yet. Can you create a new issue for this?

**Comment by bartman081523** [comment]
Yes, of course. I will do that.

**Comment by bartman081523** [comment]
#383

**Pull request merged**
