### PR TITLE
supporting http proxies

### PR DESCRIPTION
**Pull request by chrisptang**
supporting http proxies for regions that not able to connect to huggingface.co directly

by adding new command line arg:proxy, users are allowed to specify local or remote http(s) proxies for model downloading. this is helpful for users that has no direct access to huggingface.co, for example, China.

### CODE REVIEW

**Comment by sofronaspe** [comment]
Please add exception checks in case the proxy isn't available to gracefully fail the script.

**Comment by Ph0rk0z** [comment]
Can your system not run everything through the proxy?

**Comment by RedisOptimal** [comment]
The same problem traped me for several hours, until that i remember https_proxy variable. It's not necessary to change code.

Setting this environment variable before run:
`
export https_proxy="https://foo:bar@xxxx.com"
export https_proxy="socks5://127.0.0.1:8080"
`

**Comment by oobabooga** [comment]
Consensus seems to be that changing the webui code is not necessary for this

**Pull request closed without merging**
