### PR TITLE
Support the GPTCache to reduce the model Response Time

### PR DESCRIPTION
**Pull request by SimFG**
Added a cache function to LLM, which can reduce request response time if the cache is hit. This feature is disabled by default and can be enabled through the `--enable-init-gptcache` configuration. Hope this feature will improve the current project

By default, the ui will not be changed, and there will be two checkboxes after opening.
image

testing
WZOAHYqc7q

### CODE REVIEW

**Comment by SimFG** [comment]
@oobabooga please help me check it if you think it's suitable this project

**Comment by Ph0rk0z** [comment]
So this caches replies and returns the same answer if you ask the same question? So only useful for a multi-user environment?

**Comment by SimFG** [comment]
The questions don’t need to be exactly the same, just similar. If you are not satisfied with the cached answer, you can skip the cache so that you can get the answer again

**Comment by Ph0rk0z** [comment]
Definitely looks helpful for a multi-user service and then not letting them skip the cache.

**Comment by SimFG** [comment]
@Ph0rk0z have something updated? :)

**Comment by Ph0rk0z** [comment]
Lol, not yet.

**Comment by oobabooga** [comment]
This is an interesting idea, but I think that it should be an extension. It should be possible to create a custom_generate_reply that returns the cached reply if "question" is in the database, and otherwise calls the regular generate_reply 

https://github.com/oobabooga/text-generation-webui/blob/main/docs/Extensions.md#custom_generate_reply-example

**Pull request closed without merging**
