### PR TITLE
Preserve selected character on refresh/reload

### PR DESCRIPTION
**Pull request by bmoconno**
This will cause the selected character to remind selected if the UI is refreshed or closed/re-opened without shutting down the server.

### CODE REVIEW

**Comment by bmoconno** [comment]
Found a bug.

**Comment by bmoconno** [comment]
Fixed.

**Comment by oobabooga** [comment]
The problem is that `shared.settings['instruction_template']` can be dynamically set while switching models, while the event handler definition is static

**Comment by oobabooga** [comment]
Not a good solution. If I load the interface in chat mode, select instruct mode, and refresh, it returns to chat mode

If/else statements don't belong to event handler definitions

**Comment by bmoconno** [comment]
Thanks for the input. I'll think about a different solution, unless you think it's not worth pursuing.

**Comment by oobabooga** [comment]
After this change the character already persists, as the "character_menu" dropdown is updated with the current character every time the page reloads https://github.com/oobabooga/text-generation-webui/commit/b1ee674d75fca92c638e967118addb796a34a9b0

**Comment by bmoconno** [comment]
Ahh nice, didn't see that yet. Thanks!

**Pull request closed without merging**
