### PR TITLE
Use two image captioning sources

### PR DESCRIPTION
**Pull request by dibrale**
Concatenate captions from 'Salesforce/blip-image-captioning-large' and 'nlpconnect/vit-gpt2-image-captioning' for a more elaborate description of the input. This modification produces desirable results for me in chat-oriented scenarios, but requires additional HD resources. 

I am adding this as a pull request in case there's any interest. Consider additional testing before merging.

### CODE REVIEW

**Comment by Brawlence** [comment]
Do you have an example of what the final captioning result looks like with 2 sources?

**Comment by dibrale** [comment]
I was going to gather some results to include with the pull request, but the move to new weights broke my llama-13b-4bit. My llama-7b has attention deficit (and with a high enough temperature parameter, hyperactivity) disorder, so I'll need to get a bunch of stuff working again before I can post a non-cherrypicked comparison with stable parameters.

vit-gpt2-image-captioning appears to have very reasonable CPU performance, and the move to blip-image-captioning-large from blip-image-captioning-base did not create a noticeable increase captioning time. I chose to share this code sooner rather than later so people can play with it and/or break it if they feel like doing so, but I'll try to post more performance details as opportunity permits.

**Comment by dibrale** [comment]
Reopening the branch, as I closed it by accident. Was trying to clean things up before adding a code update, but I'm clearly still working my way through the GitHub interface.

**Comment by dibrale** [comment]
So, renaming branches does not work as I expected - just wanted a more descriptive name than 'patch-1 for it. Thank you for bearing with me.

**Comment by dibrale** [comment]
### **Image Strips and Plain Language Wrapper**

I've been able to further improve results using procedures loosely inspired by [retinotopic mapping](https://en.wikipedia.org/wiki/Retinotopy):

  **1.** Split input into two horizontal strips and two vertical strips.
  **2.** Feed these along with the whole image into the prompt using a plain language wrapper that communicates uncertainty in captioning.
  **3.** Instruct the LLM how to put the resulting descriptions together and encourage it to provide meaningful output. 

These are included in the foregoing commit. It takes about 20 seconds on an AMD EPYC Rome 7282 2.8GHz 16-core CPU to generate the prompt in this fashion, which is a reasonable trade-off in my opinion. I've gathered data to illustrate this using methods described [previously ](https://github.com/oobabooga/text-generation-webui/pull/607#issuecomment-1487712333) in this thread. The only modification I made since then was use of a shorter context in order to avoid having to use the `--no-cache` option for generation. The new context for the LLaMA character is as follows:

> LLaMA's Persona: LLaMA's primary function is to interact with users through natural language processing, which means it can understand and respond to text-based queries in a way that is similar to how humans communicate with each other. It's trained on vast amounts of data and algorithms that allow it to generate responses based on patterns and associations in language. Its goal is to provide helpful and informative responses to the best of it's abilities within the scope of it's programming and knowledge.

Comparing this informally with (CUDA out of memory-ridden) generations that used the longer context did not seem to cause responses to deteriorate, so I kept the abbreviated context. Below is some information regarding the test images, captioning times, and five non-cherrypicked descriptions as generated by the LLM for each image.

---
### _Corgi_
73.61 KB, JPEG, 910 x 607
Image captioning prompt generated in 19.34 seconds

> Hello again! Here's what I see in your picture:

> The picture shows a dog on a train track with a dog.

> The picture shows a dog sitting on a rock wall, or possibly a small dog standing in the middle of a forest.

> The picture you sent me was of a dog sitting on a train track.

> The picture shows a large dog sitting on a train track with a smaller dog. There are trees and bushes around them.

---
### _Vegetables_
103.80 KB, JPEG, 861 x 666
Image captioning prompt generated in 19.34 seconds

> The image shows a table with a variety of vegetables on it. There appears to be some carrots and onions on the table as well.

> The picture you sent me shows a group of vegetables and vegetables on a table. A pile of carrots sits next to a bunch of onions.

> Hello again! I hope you don't mind if I ask some follow up questions about the picture you sent me.

> Hello again! Here is what I found out about the image you sent me.
> I see a lot of different objects in the picture. Some of them look like vegetables, others look like fruit. There is also a table and some kind of knife.
> Do you want to know more about what I saw?

> The picture shows a close up of a group of vegetables and vegetables on a table, or maybe vegetables on a cutting board.

---
### _Llama_
498.72 KB, JPEG, 1539 x 2048
Image captioning prompt generated in 20.61 seconds

> The image you provided shows a close up of a llama with sheep in the background. There appears to be a white sheep standing on top of a lush green field.

> The picture you sent me appears to be a llama with sheep in the background.

> The image you provided shows a llama in a field with a white sheep.

> The image you sent me appears to be a close up of a llama with sheep in the background.

> The picture you sent me appears to be a close up of a llama with sheep in the background.

---
The model still struggles when there a lot of different objects in the image, but there seem to be fewer transformer loops and non-answers - at least with the parameters I've been using. There is more attention to multiple features within the image. Hallucinations due to miscaptioning upstream of the prompt mostly propagate only if they are persistent.

**Comment by dibrale** [comment]
### **DeepDanboory Integration and UI Options**

This version of the extension can now use [DeepDanbooru](https://github.com/KichangKim/DeepDanbooru) tagging to help generate prompts, and it can do so in any combination with the other two methods. Image strip analysis can also be toggled. Some new UI elements have been introduced to enable these features. In order to minimize clutter for those who do not wish to use it, the checkbox and settings specific to DeepDanbooru will only load if the `deepdanbooru` module can be imported by the script. 

send_interface_danbooru
---
DeepDanbooru tagging for image captioning was inspired by [this Reddit post](https://www.reddit.com/r/StableDiffusion/comments/10upvdq/an_incredible_workflow_to_caption_images/). While the post talks about sending a tag list to ChatGPT, this particular implementation integrates directly with any local model. The injection of tags markedly improves caption quality, particularly where there are human elements in the image and the image itself is complex. The tag score cutoff value can be modified to include more or fewer tags, with a corresponding trade-off in context tokens.

Output from the available inference networks can be used in any combination, and the plain language wrapper accounts for this when generating a prompt. Image strip analysis will be used with all selected networks if it is toggled on.

**Comment by oobabooga** [comment]
This is looking really interesting! =)

**Comment by oobabooga** [comment]
With the rise of [multimodal pipelines](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal), I think that it's best to keep the send_pictures extension simple so that it can serve as a starting point for similar extensions.

@dibrale I invite you to host your version of `send_pictures` and submit it to [text-generation-webui-extensions](https://github.com/oobabooga/text-generation-webui-extensions) if you are interested.

**Pull request closed without merging**
