### PR TITLE
subpath support for gradio

### PR DESCRIPTION
**Pull request by catalpaaa**
gradio looks for / for all its suff even if its reverce proxied.

some related issue for more context 

- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8897
- https://github.com/gradio-app/gradio/issues/3472

this shit is finally fixed, i got sooooooooooooooooo happy

also maybe bump gradio to 3.28, i think it fixed some symlinks thingy

### CODE REVIEW

**Comment by catalpaaa** [comment]
also fixes https://github.com/oobabooga/text-generation-webui/issues/629

**Comment by oobabooga** [comment]
How to test this?

**Comment by catalpaaa** [comment]
> How to test this?

do a reverse proxy with nginx with some subpath, then boot with the same --subpath

heres my nginx config:
```
location /textgen/ {
			proxy_pass	http://localhost:1234/;
			proxy_redirect / /textgen/;
			proxy_cookie_path / /textgen/;
		}
```

**Comment by catalpaaa** [comment]
> How to test this?

i can show you a on/off demo on my personal server if you have a way to share it privately

**Comment by oobabooga** [comment]
Is FastAPI guaranteed to be installed?

**Comment by catalpaaa** [comment]
> Is FastAPI guaranteed to be installed?

for me, it came with gradio

you can put it in req tho

**Comment by catalpaaa** [comment]
> Is FastAPI guaranteed to be installed?
fastapi is a dependence of gradio, it should be fine

**Comment by superwhyun** [comment]
It was a bug of gradio, and it is fixed a few days ago by the gradio teams.

just add your subpath into the _root_path_ parameter of the gradio.launch()

in server.py:1010
...
shared.gradio['interface'].launch(..., auth=auth, root_path=**"/subpath"**)
...

**Comment by catalpaaa** [comment]
> It was a bug of gradio, and it is fixed a few days ago by the gradio teams.
> 
> 
> 
> just add your subpath into the _root_path_ parameter of the gradio.launch()
> 
> 
> 
> in server.py:1010
> 
> ...
> 
> shared.gradio['interface'].launch(..., auth=auth, root_path=**"/subpath"**)
> 
> ...
> 
> 

Thx god it's fixed, I'll test it out and update this pr

**Comment by xiaoxinganling** [comment]
however, i still occur this problem when the nginx. proxy_redirect exists two more levels, such as /demo/textgen. How can i solve this problem, except changing 'demo/textgen' as '/textgen'...

**Comment by xiaoxinganling** [comment]
> however, i still occur this problem when the nginx. proxy_redirect exists two more levels, such as /demo/textgen. How can i solve this problem, except changing 'demo/textgen' as '/textgen'...

sorry, it's my fault, please regard this problem...

**Pull request closed without merging**
