### PR TITLE
Make new chat menu optional

### LINKED ISSUE #3907: I would like to see the old chat UI returned
Hello,
 I have been using text-generation-ui for a few months now and am happy about every further development that has been incorporated into the project. Thank you for that.

However, I would like to express a wish. After today's update I discovered that the controls I use most often are hidden behind a hamburger menu. In my opinion, the usability suffers. I would simply like to have the buttons under the input line back. Maybe as a selection option?

Ironically, the controls I never use are left within easy reach. (I've never used "Start relpy with", I only use chat mode and I never change the chat style.)

### PR DESCRIPTION
**Pull request by missionfloyd**
## Checklist:
- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

Adds an `--old-chat-menu` flag.

Fixes #3907

### CODE REVIEW

**Comment by BadisG** [comment]
Not all heroes wear capes!

**Comment by oobabooga** [comment]
This will likely break the UI in nontrivial ways in the future, and it also makes the code base more complex. For instance, the buttons are not aligned:

print

I guess it should be possible to move the new `.hover-menu` to a fixed position on the left with pure CSS as an extension if you feel like the new keyboard shortcuts are not enough.

**Comment by Carolinabanana** [comment]
Put. The. Old. Button. Layout. Back.

**Comment by BadisG** [comment]
@Carolinabanana You can have them back now, you have to use the --chat_buttons flag

**Pull request closed without merging**
