### PR TITLE
Make llama.cpp read prompt size and seed from settings

### PR DESCRIPTION
**Pull request by DGdev91**
Prompt settings and seed shouldn't be hardcoded, the user should be hardcoded, the user should be able to set them.
with this PR, the code uses the values from settings, and fall backs to the old hardcoded values if that setting value is not set.

Also, i was trying to make my AutoGPT fork and the WebUI work together using the "openai" plugin. AutoGPT is made with GPT3.5/4 in mind, and assumes a larger context size than llama, so the hard limit imposed by the webui prevents it from working (it's also written in the pugin's readme https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai)
But it should be actually possible to make it use a larger prompt context and (kinda) make it work, or at least make easier for people to try that.

### CODE REVIEW

**Comment by oobabooga** [comment]
settings.json is for interface defaults (slider values, checkboxes). this should be new command-line arguments, with corresponding checkboxes in the models tab

**Comment by DGdev91** [comment]
> settings.json is for interface defaults (slider values, checkboxes). this should be new command-line arguments, with corresponding checkboxes in the models tab

Oh, right, sorry.
Anyway, these values can already be set from the interface. they are in the Parameters tab (not Models).
Should i use shared.gradio['chat_prompt_size'] and shared.gradio['seed'] or there's a more proper way to get those values?

**Comment by DGdev91** [comment]
> > settings.json is for interface defaults (slider values, checkboxes). this should be new command-line arguments, with corresponding checkboxes in the models tab
> 
> Oh, right, sorry. Anyway, these values can already be set from the interface. they are in the Parameters tab (not Models). Should i use shared.gradio['chat_prompt_size'] and shared.gradio['seed'] or there's a more proper way to get those values?

I'm perfectly ok to change that code accordingly, there's no need to close the PR.

**Comment by oobabooga** [comment]
The truncation_length parameter is only used in `generate_reply_HF`, not `generate_reply_custom` that uses `llamacpp_model.py`. This is a parameter that affects how the model is loaded, so for consistency with similar parameters it should be defined in modules/shared.py. See all occurences of `mlock` in the source files, adding those two new parameters is exactly the same

**Comment by DGdev91** [comment]
> The truncation_length parameter is only used in `generate_reply_HF`, not `generate_reply_custom` that uses `llamacpp_model.py`. This is a parameter that affects how the model is loaded, so for consistency with similar parameters it should be defined in modules/shared.py. See all occurences of `mlock` in the source files, adding those two new parameters is exactly the same

Ok, i'll give it a look.

...But that's true for the n_ctx parameter, wouldn't make sense to just use the existing seed parameter for llama.cpp?

**Comment by DGdev91** [comment]
@oobabooga So, i'm following your instructions... i found a possible bug.
in the cli there are no-mmap and n-gpu-layers parameters, while in the gradio config they are called no_mmap and n_gpu_layers. this means that changing these vaules don't really means anything in the software, and that can explain https://github.com/oobabooga/text-generation-webui/issues/2118.
(i also tried to set a different default value to n-gpu-layers and it's still at 0 in the UI)

i know that i opened this PR for a compleatly different matter, but since i'm touching the same code... or you prefer to have them as two separate PRs?

**Comment by oobabooga** [comment]
--no-mmap --n-gpu-layers 20 works for me

params

If I change no-mmap in the interface and reload the model, it gets updated accordingly. --n-gpu-layers requires an additional special compilation step to work as described in the docs

**Comment by oobabooga** [comment]
> > The truncation_length parameter is only used in `generate_reply_HF`, not `generate_reply_custom` that uses `llamacpp_model.py`. This is a parameter that affects how the model is loaded, so for consistency with similar parameters it should be defined in modules/shared.py. See all occurences of `mlock` in the source files, adding those two new parameters is exactly the same
> 
> Ok, i'll give it a look.
> 
> ...But that's true for the n_ctx parameter, wouldn't make sense to just use the existing seed parameter for llama.cpp?

It would, but seed is not a generation parameter in llamacpp (as far as I know). Instead, it is a parameter that is used at loading time

**Comment by DGdev91** [comment]
> --no-mmap --n-gpu-layers 20 works for me
> 
> params
> 
> If I change no-mmap in the interface and reload the model, it gets updated accordingly. --n-gpu-layers requires an additional special compilation step to work as described in the docs

Oh, nevermind then. i'll just stick with those settings.

> It would, but seed is not a generation parameter in llamacpp (as far as I know). Instead, it is a parameter that is used at loading time

So you wanna keep it as a separate parameter? ok. i'll name it llamacpp_seed, to make it more obvious those are different things

**Comment by DGdev91** [comment]
@oobabooga Is it fine now or there's something else to change?

**Comment by oobabooga** [comment]
It looks good, thank you!

**Pull request merged**
