### PR TITLE
correction API metadata

### PR DESCRIPTION
**Pull request by xlyric**
Hi, 
I add the metadata in the png image generated 
issue #920 

Thanks for the application 
Cordialy

### CODE REVIEW

**Comment by Brawlence** [comment]
This is not the proper way to do it

**Comment by xlyric** [comment]
I just apply the documentation ;)
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/api

`import json
import requests
import io
import base64
from PIL import Image, PngImagePlugin

url = "http://127.0.0.1:7860"

payload = {
    "prompt": "puppy dog",
    "steps": 5
}

response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)

r = response.json()

for i in r['images']:
    image = Image.open(io.BytesIO(base64.b64decode(i.split(",",1)[0])))

    png_payload = {
        "image": "data:image/png;base64," + i
    }
    response2 = requests.post(url=f'{url}/sdapi/v1/png-info', json=png_payload)

    pnginfo = PngImagePlugin.PngInfo()
    pnginfo.add_text("parameters", response2.json().get("info"))
    image.save('output.png', pnginfo=pnginfo)`

**Comment by mcmonkey4eva** [comment]
This is definitely not the correct way to do this, -but- if you actually tested and it works, that implies that the image has already had metadata the whole time, and it's being accidentally stripped by the `Image.open` call - so you can just bypass that and save the bytes directly and it will save properly with metadata.

**Comment by Brawlence** [comment]
LMAO I'm stupid

**Comment by oobabooga** [comment]
Closing this in favor of https://github.com/oobabooga/text-generation-webui/pull/1082 (thanks for the reviews, by the way)

**Pull request closed without merging**
