### PR TITLE
Superboogav2 dependency update

### PR DESCRIPTION
**Pull request by sidewaysthought**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

Update superboogav2 requirements.txt to resolve Issue #5090

### CODE REVIEW

**Comment by oobabooga** [comment]
This is a duplicate of #5067. The same comment also applies, could you check? https://github.com/oobabooga/text-generation-webui/pull/5067#issuecomment-1870405440

**Comment by sidewaysthought** [comment]
Confirmed! My issue and PR are dupes. Apologies!




________________________________

**Comment by oobabooga** [comment]
That's fine. If you can test the updated chromadb version that would be helpful.

**Comment by oobabooga** [comment]
Closing in favor of https://github.com/oobabooga/text-generation-webui/pull/5656

**Pull request closed without merging**
