### PR TITLE
basic web search extension

### PR DESCRIPTION
**Pull request by GitHub1712**
basic web search
- run server with --extensions search
- enter search: at the beginning of the prompt to start a search for the rest of the prompt.
- TODO more search engines, visit website direct, improve scraping of the pages content

### CODE REVIEW

**Comment by Malrama** [comment]
This is such a neat addition? I tied it and it really the changes the way you can use your AI.
Haven't found any errors so far. Would love to see more progress in here. An integration into the UI would be nice. However, I have no idea how that might look like.

Anyway, thank you very kindly!

**Comment by St33lMouse** [comment]
This is a critical piece of the puzzle. Hope it gets merged soon!

**Comment by eightifact** [comment]
it really works. i copied the extension search folder and script.py into a different build.

**Comment by oobabooga** [comment]
I have tried the extension and it didn't work. Duckduckgo returns this text:

```
'If this error persists, please let us know: error-lite@duckduckgo.com'
```

**Pull request closed without merging**
