### PR TITLE
Make new chat menu optional

### PR DESCRIPTION
**Pull request by missionfloyd**
## Checklist:
- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

I fixed the menu alignment. (https://github.com/oobabooga/text-generation-webui/pull/3913#issuecomment-1719492424)

https://github.com/oobabooga/text-generation-webui/assets/4073789/4c573a1e-412a-4676-9ce1-67da16bfbe40

### CODE REVIEW

**Comment by oobabooga** [comment]
I still don't think that this is a good solution. A compromise I can think of is to create new `Regenerate` / `Continue` / `Remove last` buttons similar to this on LM Studio:

test

These buttons would be defined in a new `gr.HTML` element that would be shown on desktop only. It could be placed on the same line as the typing dots and the "Show controls" checkbox.

This way, the most used buttons would be on display while keeping the rest of the new design intact.

**Comment by BadisG** [comment]
We just want to see the buttons back, like it was before, that's all we're asking

**Comment by missionfloyd** [comment]
Something like that?
image

**Comment by oobabooga** [comment]
No, I was thinking of something similar to this:

concept

The 3 new buttons would be custom HTML buttons with new CSS styles, not Gradio buttons, and their `onclick` would be javascript events that click on the main buttons, for instance:

```
document.getElementById('Regenerate').click();
```

**Pull request closed without merging**
