### PR TITLE
[extensions/openai] various fixes

### LINKED ISSUE #2505: [extensions/openai] Improve error handling with no model loaded
### Describe the bug

I was using a few days old version of webui (githash `6627f7f`) and openAI extension worked great.

After updating to latest ([19f7868](https://github.com/oobabooga/text-generation-webui/commit/19f78684e6d32d43cd5ce3ae82d6f2216421b9ae)), openAI extension throws an error on the `/completions` endpoint.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

* enable openai extension
* run the completions api (via any openai supporting tool)

### Screenshot

_No response_

### Logs

```python
127.0.0.1 - - [03/Jun/2023 08:52:27] "POST /v1/chat/completions HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 41928)
Traceback (most recent call last):
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/mnt/nvbig/ai/text-generation-webui/extensions/openai/script.py", line 355, in do_POST
    system_token_count = len(encode(system_msg)[0])
  File "/mnt/ai/text-generation-webui/modules/text_generation.py", line 44, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
AttributeError: 'NoneType' object has no attribute 'encode'
----------------------------------------
```

### System Info

```shell
linux
```

### PR DESCRIPTION
**Pull request by matatonic**
* cleanup models list
* cleanup & improve stopping strings handling
* Fix data type for some request params
* Improve error handling, Fixes #2505
* Fixes https://github.com/oobabooga/text-generation-webui/issues/2516
* Replaces https://github.com/oobabooga/text-generation-webui/pull/2525
* Replaces https://github.com/oobabooga/text-generation-webui/pull/2532
* Partially revert recent changes from https://github.com/oobabooga/text-generation-webui/pull/2409, https://github.com/oobabooga/text-generation-webui/pull/2423
* Confirmed still working with anse and openai python clients.

FYI: @Pb-207, @oceanplexian - if you have time to test this fix is working for you it would be greatly appreciated (sorry for the notification spam but the fix is now here, I will remove the old PR)

### CODE REVIEW

**Comment by LoopControl** [comment]
Tested the no-model-loaded case now. Client side returns HTTP 500 with `{"error": {"message": "No model loaded.", "code": 500, "type": "APIError", "param": ""}}`

Text-gen outputs, `127.0.0.1 - - [05/Jun/2023 14:27:36] "POST /v1/chat/completions HTTP/1.1" 500 -` which is nicer.

:+1:

**Comment by oceanplexian** [comment]
Tested with Anse (works) and with the go-openai client (https://github.com/sashabaranov/go-openai), and both seem to be working without any regressions 👍

**Comment by matatonic** [comment]
That's great, thanks so much!

**Comment by Pb-207** [comment]
> * cleanup models list
> * cleanup & improve stopping strings handling
> * Fix data type for some request params
> * Improve error handling, Fixes [[extensions/openai] Improve error handling with no model loaded #2505](https://github.com/oobabooga/text-generation-webui/issues/2505)
> * Fixes [OpenAi API JSONDecodeError #2516](https://github.com/oobabooga/text-generation-webui/issues/2516)
> * Replaces [Better error message when using OpenAI extension, but forgetting to load a model #2525](https://github.com/oobabooga/text-generation-webui/pull/2525)
> * Replaces [[extensions/openai] Fixes #2516, +partially revert chunk length change when streaming #2532](https://github.com/oobabooga/text-generation-webui/pull/2532)
> * Partially revert recent changes from [[extensions/openai] Add cross-origin headers, chunked responses, update [done] termination #2409](https://github.com/oobabooga/text-generation-webui/pull/2409), [[extensions/openai] cross_origin + chunked_response (updated fix) #2423](https://github.com/oobabooga/text-generation-webui/pull/2423)
> * Confirmed still working with anse and openai python clients.
> 
> FYI: @Pb-207, @oceanplexian - if you have time to test this fix is working for you it would be greatly appreciated (sorry for the notification spam but the fix is now here, I will remove the old PR)

Tested with [gpt_academic](https://github.com/binary-husky/gpt_academic) and [chatgpt-mirai-qq-bot](https://github.com/lss233/chatgpt-mirai-qq-bot), both are working well. This s an excellent extension, thx for your contribution.

**Pull request merged**
