### PR TITLE
Add tensor split support for llama.cpp

### PR DESCRIPTION
**Pull request by shouyiwang**
When running a large model across two GPUs in llama.cpp of webui, it currently loads the model by default in a half-by-half manner. However, the way it splits the model into halves is not precise, which often leads to OOM.

Implementing the --tensor-split parameter will address this problem by empowering users to define the proportion of the model distributed across multiple GPUs.

### CODE REVIEW

**Comment by shouyiwang** [comment]
@oobabooga 
Thank you for merging this into dev branch. But please don't merge it into main branch at the moment.
The reason is [Llama.cpp changed its tensor_split from an array to a pointer](https://github.com/ggerganov/llama.cpp/commit/ae178ab46bfd6ecb2422da5dad441a4e2fef8b7e) 4 days ago, so tensor_split in llama-cpp-python doesn't work anymore.
[I submitted a PR ](https://github.com/abetlen/llama-cpp-python/pull/523)to llama-cpp-python yesterday, but it hasn't been merged yet.
I will inform you when my PR has been merged into llama-cpp-python.

**Comment by oobabooga** [comment]
Thanks for letting me know @shouyiwang. I'll wait for your confirmation then.

**Comment by shouyiwang** [comment]
@oobabooga 
Llama-cpp-python has just released a new version for the first time in the last three weeks. My PR is included in this new version! 
I think it is time to merge this PR into main branch.

**Comment by oobabooga** [comment]
@shouyiwang thanks for the heads up. I had already merged the PR, then reverted it, and now I reverted the revert in https://github.com/oobabooga/text-generation-webui/pull/3610/files. Can you check if it still works?

**Comment by shouyiwang** [comment]
@oobabooga 
I tested the latest main branch, and the tensor split function works fine. 
Thanks!

**Comment by Thireus** [comment]
@oobabooga, can it be merged into main?

**Pull request merged**
