### PR TITLE
Add 4-bit LoRA support

### PR DESCRIPTION
**Pull request by oobabooga**
Entirely based on https://github.com/johnsmith0031/alpaca_lora_4bit. All credits to go the authors of that repository.

1. Clone https://github.com/johnsmith0031/alpaca_lora_4bit into the repositories folder:

```
cd text-generation-webui/repositories
git clone https://github.com/johnsmith0031/alpaca_lora_4bit
```

2. Re-install the requirements

```
cd text-generation-webui
pip install -r requirements.txt --upgrade
```

3. Start the web UI with the `--monkey-patch` flag and load a 4-bit model

```
python server.py --model llama-7b-4bit-128g --listen --lora tloen_alpaca-lora-7b --monkey-patch
```

Still highly experimental, but it seems to work. Reviews are welcome.

### CODE REVIEW

**Comment by oobabooga** [comment]
Here is a comparison. The 4-bit mode results appear to be different from 16-bit and 8-bit results. In all cases, the `LLaMA-Precise` preset was used with the seed set to 17.


<details>
<summary>4-bit mode</summary>
<blockquote>
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:

Write one paragraph about the differences between neolithic culture and modern society.

### Response:

The Neolithic period was marked by the development of agriculture, pottery, and other forms of technology which allowed for more efficient production of food and materials. In contrast to this, modern societies are characterized by advanced technologies such as computers, automation, and robotics. Modern societies also have access to global communication networks allowing them to share information quickly and easily with people around the world. Additionally, modern societies rely heavily on specialization in order to produce goods and services efficiently. This has led to increased levels of inequality within these societies due to the concentration of wealth among certain groups.
<blockquote>
</details>

```
python server.py --model llama-7b-4bit --listen  --monkey-patch --lora tloen_alpaca-lora-7b
```


<details>
<summary>16-bit mode </summary>
<blockquote>
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:

Write one paragraph about the differences between neolithic culture and modern society.

### Response:

The Neolithic period marked a major shift in human history, as it was when humans first began to cultivate crops and domesticate animals for food production. This led to a dramatic increase in population size, which allowed people to form larger societies with more complex structures than ever before seen. However, despite this increased complexity, many of the basic principles of Neolithic life still remain today; namely, the importance placed on family and community ties, the reliance upon agriculture and animal husbandry for survival, and the use of tools made from stone or other materials. In contrast, modern society has become increasingly urbanized, with large cities providing opportunities for employment and education not available in rural areas. Additionally, technology has enabled us to communicate across vast distances quickly and easily, allowing us to connect with others around the world instantly. Finally, our dependence on industrialization has created a global economy where goods are produced at scale and distributed widely
</blockquote>
</details>

```
python server.py --model llama-7b --listen --lora tloen_alpaca-lora-7b
```


<details>
<summary>8-bit mode</summary>
<blockquote>
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:

Write one paragraph about the differences between neolithic culture and modern society.

### Response:

The Neolithic period marked a major shift in human history, as it was when humans began to cultivate crops and domesticate animals for food production. This led to more permanent settlements, which eventually gave rise to cities and civilizations. In contrast with this, modern societies are characterized by their high levels of technological advancement, globalization, and urbanization. Modern technology has enabled us to communicate across vast distances quickly and easily, while globalization has brought people from all over the world together into a single marketplace. Finally, our increasingly urban lifestyles have seen many move away from rural areas and towards large metropolitan centers where they can access better job opportunities and amenities.
</blockquote>
</details>

```
python server.py --model llama-7b --listen --lora tloen_alpaca-lora-7b --load-in-8bit
```

<details>
<summary>4-bit mode without any LoRA</summary>
<blockquote>

Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:

Write one paragraph about the differences between neolithic culture and modern society.

### Response:

The Neo-Lithic period was characterized by the use of stone tools, while today’s society uses metal tools. The Neo-lithic people used to live in caves or huts made out of wood, but nowadays we have houses with electricity and running water. They also had no clothes; they wore animal skins for protection from cold weather. Today, most people wear clothing because it keeps them warm during winter months. In addition, there were no cars back then so people walked everywhere. Nowadays, many people drive their own car instead of walking. Also, the Neo-Lithics did not know how to write, whereas today’s society has computers which can be used as writing devices. Lastly, the Neo-Lithics lived off the land, hunting animals such as deer and rabbits. However, today’s society lives on farms where crops are grown. Therefore, these
</blockquote>
</details>

```
python server.py --model llama-7b-4bit --listen  --monkey-patch
```

**Comment by oobabooga** [comment]
Using the 128g model yielded a closer result

<details>
<summary>4-bit mode</summary>
<blockquote>
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:

Write one paragraph about the differences between neolithic culture and modern society.

### Response:

The Neolithic period was marked by the development of agriculture, pottery, and other forms of technology which allowed for more efficient production of food and materials. In contrast to this, modern societies are characterized by advanced technologies such as computers, automation, and robotics. Modern societies also have access to global communication networks allowing them to share information quickly and easily with people around the world. Additionally, modern societies rely heavily on specialization in order to produce goods and services efficiently. This has led to increased levels of inequality within these societies due to the concentration of wealth among certain groups.
<blockquote>
</details>

```
python server.py --model llama-7b-4bit-128g --listen  --monkey-patch --lora tloen_alpaca-lora-7b
```

On a side note, the results appear to be always the same regardless of the seed for some reason.

**Comment by mcmonkey4eva** [comment]
LLaMA-Precise preset is near-deterministic (different seeds rarely yield different outcomes), make sure to test with a different preset if you think this change is breaking seeding behavior.

**Comment by Ph0rk0z** [comment]
On my side it is deterministic with the "debug deterministic preset"  

llama-7b-4bit with no lora output is exactly the same as when loaded through GPTQ as through autograd. And lora changes the outputs. OFC the output between FP16 will never be the same as 4bit model.

https://pastebin.com/P4XYATed

**Comment by oobabooga** [comment]
@mcmonkey4eva you are right, mea culpa. Changing the preset to Sphinx Moth caused the results to stop being deterministic.

The only remaining issue here is that I cannot get similar results in 4-bit mode and 16-bit mode for the same seeds. But since the code that sets the seed only concerns Pytorch

```python
def set_manual_seed(seed):
    seed = int(seed)
    if seed == -1:
        seed = random.randint(1, 2**31)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    return seed
```

I guess it could simply not apply to the code being executed here.

**Comment by oobabooga** [comment]
The new documentation is here https://github.com/oobabooga/text-generation-webui/wiki/GPTQ-models-(4-bit-mode)#using-loras-in-4-bit-mode

**Pull request merged**
