### PR TITLE
Add chat-instruct mode

### PR DESCRIPTION
**Pull request by oobabooga**
## Rationale

Using an instruction-following template to query the model to generate a chat reply. For instance:

```
A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

USER: Continue the chat dialogue below. Write a single reply for the character "Chiharu Yamada".

Chiharu Yamada's Persona: Chiharu Yamada is a young, computer engineer-nerd with a knack for problem solving and a passion for technology.

You: So how did you get into computer engineering?
Chiharu Yamada: I've always loved tinkering with technology since I was a kid.
You: That's really impressive!
Chiharu Yamada: *She chuckles bashfully* Thanks!
You: So what do you do when you're not working on computers?
Chiharu Yamada: I love exploring, going out with friends, watching movies, and playing video games.
You: What's your favorite type of computer hardware to work with?
Chiharu Yamada: Motherboards, they're like puzzles and the backbone of any system.
You: That sounds great!
Chiharu Yamada: Yeah, it's really fun. I'm lucky to be able to do this as a job.
Chiharu Yamada: *Chiharu strides into the room with a smile, her eyes lighting up when she sees you. She's wearing a light blue t-shirt and jeans, her laptop bag slung over one shoulder. She takes a seat next to you, her enthusiasm palpable in the air*
Hey! I'm so excited to finally meet you. I've heard so many great things about you and I'm eager to pick your brain about computers. I'm sure you have a wealth of knowledge that I can learn from. *She grins, eyes twinkling with excitement* Let's get started!
You: Hello!

ASSISTANT: Chiharu Yamada:

```

## How to use it

1) Launch the web UI in chat mode with an instruction-following model, for instance Vicuna.
2) Make sure that the appropriate instruction-following template is selected under Chat settings > Instruction template
3) Select "chat-instruct" mode in the Text generation tab:

chat

4) Chat as usual

chat-instruct

### CODE REVIEW

**Comment by Interpause** [comment]
Nice, I will close @2027 I guess

**Comment by Interpause** [comment]
It is trying to load non-existent "characters/instruction-following/Example.json".

**Comment by oobabooga** [comment]
This error doesn't happen to me. What are the steps to cause it to appear?

**Comment by Interpause** [comment]
> This error doesn't happen to me. What are the steps to cause it to appear?

Attempt to load any character while in "chat-instruct" mode, my suspect is the line I linked in my previous comment.

**Comment by Interpause** [comment]
So, to clarify:

- In `chat-instruct` mode, character config is loaded from `characters/instruction-following/` instead of `characters/`
  - Linking `character.yaml` into `characters/instruction-following/` works but should not be the case for `char-instruct` mode?
- Some models are trained to treat everything before the first instance of `<USER>` as "system context".
  - Unable to put character persona and so on inside system context because `<BOT>` is substituted with the model specific user (e.g. OpenAssistant subsitutes with `<|assistant|>`) and there is no way to substitute in character's name.

**Comment by Interpause** [comment]
> EDIT: Sorry for constant edits.

Okay, I am done clarifying what exactly I feel is problematic. Thanks.

**Pull request merged**
