### PR TITLE
More robust and error prone training

### PR DESCRIPTION
**Pull request by FartyPants**
Here are couple of my last weeks changes to training flow

- Makes sure the model is reloaded if needed. Once you run training, the model is dirty and you should not continue training or run another training without reloading model - this will do it automatically
- adds optional Add EOS - this will then add EOS to all items in datased, in case of text file it will add EOS at the hard cut boundaries
- add min_char for plain text. When using with hard cut it will ignore small blocks that are <= min_char, for example page number, titles etc.
- check if you don't have double BOS. This is my take on the discussion in https://github.com/oobabooga/text-generation-webui/pull/3035 
- displays projection used for training. I am currently experimenting with q,k,v,o LoRA training and I will see in the future if it is worth adding a switch to interface or not. q,k,v,o adds around twice as much parameters to LoRA, possibly making more robust LoRAs. (the other possibility that the result will be negligible) so we will see.

### CODE REVIEW

**Comment by oobabooga** [comment]
@FartyPants the changes look good to me. Could you please merge the dev branch? I have merged several PRs related to training and there are some conflicts. I think it's better if you do it to prevent me from introducing bugs.

**Comment by FartyPants** [comment]
I had look at the dev, did we loose the replace('\r' in plaintext... it needs to go back IMHO and for the folders too

`   # == Prep the dataset, format, etc ==
    if raw_text_file not in ['None', '']:
        train_template["template_type"] = "raw_text"
        logger.info("Loading raw text file dataset...")
        fullpath = clean_path('training/datasets', f'{raw_text_file}')
        fullpath = Path(fullpath)
        if fullpath.is_dir():
            logger.info('Training path directory {}'.format(raw_text_file))
            raw_text = ""
            file_paths = sorted(fullpath.glob('*.txt'), key=lambda path: natural_keys(path.name))
            for file_path in file_paths:
                if file_path.is_file():
                    with file_path.open('r', encoding='utf-8') as file:
                        raw_text += file.read().replace('\r', '')

                    logger.info(f"Loaded training file: {file_path.name}")
        else:
        with open(clean_path('training/datasets', f'{raw_text_file}.txt'), 'r', encoding='utf-8') as file:
            raw_text = file.read().replace('\r', '')
`

**Comment by oobabooga** [comment]
Well noted, I'm trying to find the commit that removed it

**Comment by oobabooga** [comment]
Okay that was 5d513eea222f29f1e1c1b0a57500134873bf7c0f

I added it back here https://github.com/oobabooga/text-generation-webui/commit/30f37530d506aad0fd41c87e1ec0aa8aaf897e71

**Comment by FartyPants** [comment]
seems resolved... hopefully no indentation issues.

**Comment by oobabooga** [comment]
Looks good now, thanks!

**Pull request merged**
