### PR TITLE
Stop the bot from talking for you in chat mode

### PR DESCRIPTION
**Pull request by oobabooga**
For #513

### CODE REVIEW

**Review by RandomInternetPreson — COMMENTED** [review]
I made this change and it didn't alter the output.  I'm assuming you made this change to avoid the AI having a P1: and P2: conversation on it's own?

I've found that if you give yourself and the AI a name prior to the conversation instead of the default "Person 1" "Person 2" The AI will no longer have the P1: P2: conversations on its own.

**Comment by oobabooga** [comment]
It shouldn't alter the output, it should only stop the text generation in case the bot starts talking as if it was you like

Bot: Hey, how are you?
You: I'm fine

The goal is to prevent

> You: I'm fine

From ever appearing, where "You" is your name.

**Comment by Ph0rk0z** [comment]
Oh they will happily say your name and their own name too. But so far so good.

**Comment by oobabooga** [comment]
I probably messed something up.

**Comment by oobabooga** [comment]
Some big simplifications in the code now.

**Pull request merged**
