### PR TITLE
Fix error when bos_token_id is None

### PR DESCRIPTION
**Pull request by belladoreai**
Issue: https://github.com/oobabooga/text-generation-webui/pull/6050#issuecomment-2134317732

Note that I have not tested this PR at all. (I can't run big models like the one that this error was reported on.)

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by TheLounger** [comment]
I've tried a bunch of other models and none seem to have this issue, except [alfred-40B-1023-GGUF](https://huggingface.co/TheBloke/alfred-40B-1023-GGUF) 🤔
This PR seems to fix it, but I don't understand why.

Here's the error again, without this fix:

```
  File "/home/lounger/ai/text/webui/modules/text_generation.py", line 146, in encode
    bos_tensor = torch.tensor([[shared.tokenizer.bos_token_id]])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Could not infer dtype of NoneType
```

Here's the model's metadata upon loading:

```
llama_model_loader: loaded meta data with 18 key-value pairs and 484 tensors from models\40B-GGUF-Q4__alfred-1023-8K\alfred-40b-1023.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = falcon
llama_model_loader: - kv   1:                               general.name str              = Falcon
llama_model_loader: - kv   2:                      falcon.context_length u32              = 2048
llama_model_loader: - kv   3:                  falcon.tensor_data_layout str              = jploski
llama_model_loader: - kv   4:                    falcon.embedding_length u32              = 8192
llama_model_loader: - kv   5:                 falcon.feed_forward_length u32              = 32768
llama_model_loader: - kv   6:                         falcon.block_count u32              = 60
llama_model_loader: - kv   7:                falcon.attention.head_count u32              = 128
llama_model_loader: - kv   8:             falcon.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:        falcon.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 15
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,65024]   = [">>TITLE<<", ">>ABSTRACT<<", ">>INTR...
llama_model_loader: - kv  13:                  tokenizer.ggml.token_type arr[i32,65024]   = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  14:                      tokenizer.ggml.merges arr[str,64780]   = ["─á t", "─á a", "i n", "h e", "r e",...
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32              = 65020
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 11
llama_model_loader: - kv  17:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  242 tensors
llama_model_loader: - type q8_0:    1 tensors
llama_model_loader: - type q4_K:  151 tensors
llama_model_loader: - type q5_K:   88 tensors
llama_model_loader: - type q6_K:    2 tensors
llm_load_vocab: missing pre-tokenizer type, using: 'default'
llm_load_vocab:
llm_load_vocab: ************************************
llm_load_vocab: GENERATION QUALITY WILL BE DEGRADED!
llm_load_vocab: CONSIDER REGENERATING THE MODEL
llm_load_vocab: ************************************
llm_load_vocab:
llm_load_vocab: special tokens definition check successful ( 16/65024 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = falcon
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 65024
llm_load_print_meta: n_merges         = 64780
llm_load_print_meta: n_ctx_train      = 2048
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_head           = 128
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 60
llm_load_print_meta: n_rot            = 64
llm_load_print_meta: n_embd_head_k    = 64
llm_load_print_meta: n_embd_head_v    = 64
llm_load_print_meta: n_gqa            = 16
llm_load_print_meta: n_embd_k_gqa     = 512
llm_load_print_meta: n_embd_v_gqa     = 512
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 32768
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 2048
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 40B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 41.84 B
llm_load_print_meta: model size       = 23.70 GiB (4.87 BPW)
llm_load_print_meta: general.name     = Falcon
llm_load_print_meta: BOS token        = 11 '<|endoftext|>'
llm_load_print_meta: EOS token        = 65020 '<end_message>'
llm_load_print_meta: LF token         = 138 '├ä'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   yes
ggml_cuda_init: CUDA_USE_TENSOR_CORES: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060 Ti, compute capability 8.6, VMM: yes
llm_load_tensors: ggml ctx size =    0.51 MiB
llm_load_tensors: offloading 11 repeating layers to GPU
llm_load_tensors: offloaded 11/61 layers to GPU
llm_load_tensors:        CPU buffer size = 24271.06 MiB
llm_load_tensors:      CUDA0 buffer size =  4397.88 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =   480.00 MiB
llama_new_context_with_model: KV self size  =  480.00 MiB, K (f16):  240.00 MiB, V (f16):  240.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.25 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   682.75 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =  1050.01 MiB
llama_new_context_with_model: graph nodes  = 2168
llama_new_context_with_model: graph splits = 468
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 |
Model metadata: {'falcon.embedding_length': '8192', 'general.name': 'Falcon', 'falcon.attention.head_count_kv': '8', 'general.architecture': 'falcon', 'falcon.context_length': '2048', 'falcon.tensor_data_layout': 'jploski', 'falcon.feed_forward_length': '32768', 'falcon.block_count': '60', 'falcon.attention.head_count': '128', 'falcon.attention.layer_norm_epsilon': '0.000010', 'tokenizer.ggml.eos_token_id': '65020', 'general.file_type': '15', 'tokenizer.ggml.model': 'gpt2', 'general.quantization_version': '2', 'tokenizer.ggml.bos_token_id': '11'}

```

**Comment by TheLounger** [comment]
Not sure why it's `<|endoftext|>`, does it actually matter though?
Falcon, on which it is based [seems to have](https://huggingface.co/tiiuae/falcon-40b/raw/main/tokenizer.json) the same.
I'll test that one ([maddes8cht/tiiuae-falcon-40b-gguf](https://huggingface.co/maddes8cht/tiiuae-falcon-40b-gguf)) and see what happens...

**Comment by belladoreai** [comment]
Huh, I guess that's intentional then. I haven't ever used Falcon based models.

The second question is still unclear to me: why the bos token is being read as `None`.

**Comment by TheLounger** [comment]
Tested [tiiuae-falcon-40b-gguf](https://huggingface.co/maddes8cht/tiiuae-falcon-40b-gguf) and it's even more awkward:
```
llm_load_print_meta: BOS token        = 11 '<|endoftext|>'
llm_load_print_meta: EOS token        = 11 '<|endoftext|>'
```
But has the same problem as well.

**Comment by TheLounger** [comment]
Model is probably a little funky. Here I checked it's tokenizer types at runtime, I guess it's metadata and actual data are not in line.
```
23:10:40-045059 INFO     ===========================================================
23:10:40-046060 INFO     type(shared.tokenizer.SPECIAL_TOKENS_ATTRIBUTES): <class 'list'>
23:10:40-047561 INFO     type(shared.tokenizer.__annotations__): <class 'dict'>
23:10:40-048061 INFO     type(shared.tokenizer.__call__): <class 'method'>
23:10:40-049062 INFO     type(shared.tokenizer.__class__): <class 'type'>
23:10:40-050063 INFO     type(shared.tokenizer.__delattr__): <class 'method-wrapper'>
23:10:40-050564 INFO     type(shared.tokenizer.__dict__): <class 'dict'>
23:10:40-051564 INFO     type(shared.tokenizer.__dir__): <class 'builtin_function_or_method'>
23:10:40-052565 INFO     type(shared.tokenizer.__doc__): <class 'str'>
23:10:40-053066 INFO     type(shared.tokenizer.__eq__): <class 'method-wrapper'>
23:10:40-054066 INFO     type(shared.tokenizer.__format__): <class 'builtin_function_or_method'>
23:10:40-055067 INFO     type(shared.tokenizer.__ge__): <class 'method-wrapper'>
23:10:40-055568 INFO     type(shared.tokenizer.__getattribute__): <class 'method-wrapper'>
23:10:40-056569 INFO     type(shared.tokenizer.__getstate__): <class 'builtin_function_or_method'>
23:10:40-057570 INFO     type(shared.tokenizer.__gt__): <class 'method-wrapper'>
23:10:40-058570 INFO     type(shared.tokenizer.__hash__): <class 'method-wrapper'>
23:10:40-059571 INFO     type(shared.tokenizer.__init__): <class 'method'>
23:10:40-060572 INFO     type(shared.tokenizer.__init_subclass__): <class 'builtin_function_or_method'>
23:10:40-061072 INFO     type(shared.tokenizer.__le__): <class 'method-wrapper'>
23:10:40-062073 INFO     type(shared.tokenizer.__len__): <class 'method'>
23:10:40-063074 INFO     type(shared.tokenizer.__lt__): <class 'method-wrapper'>
23:10:40-064075 INFO     type(shared.tokenizer.__module__): <class 'str'>
23:10:40-065076 INFO     type(shared.tokenizer.__ne__): <class 'method-wrapper'>
23:10:40-065576 INFO     type(shared.tokenizer.__new__): <class 'builtin_function_or_method'>
23:10:40-066577 INFO     type(shared.tokenizer.__reduce__): <class 'builtin_function_or_method'>
23:10:40-067578 INFO     type(shared.tokenizer.__reduce_ex__): <class 'builtin_function_or_method'>
23:10:40-068580 INFO     type(shared.tokenizer.__repr__): <class 'method'>
23:10:40-069080 INFO     type(shared.tokenizer.__setattr__): <class 'method-wrapper'>
23:10:40-070581 INFO     type(shared.tokenizer.__sizeof__): <class 'builtin_function_or_method'>
23:10:40-071081 INFO     type(shared.tokenizer.__str__): <class 'method-wrapper'>
23:10:40-072082 INFO     type(shared.tokenizer.__subclasshook__): <class 'builtin_function_or_method'>
23:10:40-073083 INFO     type(shared.tokenizer.__weakref__): <class 'NoneType'>
23:10:40-073584 INFO     type(shared.tokenizer._add_tokens): <class 'method'>
23:10:40-074584 INFO     type(shared.tokenizer._additional_special_tokens): <class 'list'>
23:10:40-075586 INFO     type(shared.tokenizer._auto_class): <class 'NoneType'>
23:10:40-076086 INFO     type(shared.tokenizer._batch_encode_plus): <class 'method'>
23:10:40-077087 INFO     type(shared.tokenizer._bos_token): <class 'NoneType'>
23:10:40-078087 INFO     type(shared.tokenizer._call_one): <class 'method'>
23:10:40-078588 INFO     type(shared.tokenizer._cls_token): <class 'NoneType'>
23:10:40-079588 INFO     type(shared.tokenizer._compile_jinja_template): <class 'method'>
23:10:40-080590 INFO     type(shared.tokenizer._convert_encoding): <class 'method'>
23:10:40-081590 INFO     type(shared.tokenizer._convert_id_to_token): <class 'method'>
23:10:40-082591 INFO     type(shared.tokenizer._convert_token_to_id_with_added_voc): <class 'method'>
23:10:40-083092 INFO     type(shared.tokenizer._create_repo): <class 'method'>
23:10:40-084092 INFO     type(shared.tokenizer._decode): <class 'method'>
23:10:40-085094 INFO     type(shared.tokenizer._decode_use_source_tokenizer): <class 'bool'>
23:10:40-086094 INFO     type(shared.tokenizer._encode_plus): <class 'method'>
23:10:40-086595 INFO     type(shared.tokenizer._eos_token): <class 'tokenizers.AddedToken'>
23:10:40-087595 INFO     type(shared.tokenizer._eventual_warn_about_too_long_sequence): <class 'method'>
23:10:40-088596 INFO     type(shared.tokenizer._eventually_correct_t5_max_length): <class 'function'>
23:10:40-089097 INFO     type(shared.tokenizer._from_pretrained): <class 'method'>
23:10:40-090097 INFO     type(shared.tokenizer._get_files_timestamps): <class 'method'>
23:10:40-091098 INFO     type(shared.tokenizer._get_padding_truncation_strategies): <class 'method'>
23:10:40-091599 INFO     type(shared.tokenizer._in_target_context_manager): <class 'bool'>
23:10:40-092600 INFO     type(shared.tokenizer._mask_token): <class 'NoneType'>
23:10:40-093100 INFO     type(shared.tokenizer._pad): <class 'method'>
23:10:40-094101 INFO     type(shared.tokenizer._pad_token): <class 'NoneType'>
23:10:40-095102 INFO     type(shared.tokenizer._pad_token_type_id): <class 'int'>
23:10:40-095603 INFO     type(shared.tokenizer._processor_class): <class 'NoneType'>
23:10:40-096603 INFO     type(shared.tokenizer._save_pretrained): <class 'method'>
23:10:40-097850 INFO     type(shared.tokenizer._sep_token): <class 'NoneType'>
23:10:40-098605 INFO     type(shared.tokenizer._set_processor_class): <class 'method'>
23:10:40-099606 INFO     type(shared.tokenizer._switch_to_input_mode): <class 'method'>
23:10:40-100106 INFO     type(shared.tokenizer._switch_to_target_mode): <class 'method'>
23:10:40-101107 INFO     type(shared.tokenizer._tokenizer): <class 'tokenizers.Tokenizer'>
23:10:40-102108 INFO     type(shared.tokenizer._unk_token): <class 'NoneType'>
23:10:40-103109 INFO     type(shared.tokenizer._upload_modified_files): <class 'method'>
23:10:40-103609 INFO     type(shared.tokenizer.add_special_tokens): <class 'method'>
23:10:40-104610 INFO     type(shared.tokenizer.add_tokens): <class 'method'>
23:10:40-105611 INFO     type(shared.tokenizer.added_tokens_decoder): <class 'dict'>
23:10:40-106111 INFO     type(shared.tokenizer.added_tokens_encoder): <class 'dict'>
23:10:40-107112 INFO     type(shared.tokenizer.additional_special_tokens): <class 'list'>
23:10:40-108112 INFO     type(shared.tokenizer.additional_special_tokens_ids): <class 'list'>
23:10:40-109114 INFO     type(shared.tokenizer.all_special_ids): <class 'list'>
23:10:40-109614 INFO     type(shared.tokenizer.all_special_tokens): <class 'list'>
23:10:40-110615 INFO     type(shared.tokenizer.all_special_tokens_extended): <class 'list'>
23:10:40-111616 INFO     type(shared.tokenizer.apply_chat_template): <class 'method'>
23:10:40-112617 INFO     type(shared.tokenizer.as_target_tokenizer): <class 'method'>
23:10:40-113117 INFO     type(shared.tokenizer.backend_tokenizer): <class 'tokenizers.Tokenizer'>
23:10:40-114119 INFO     type(shared.tokenizer.batch_decode): <class 'method'>
23:10:40-115119 INFO     type(shared.tokenizer.batch_encode_plus): <class 'method'>
23:10:40-116120 INFO     type(shared.tokenizer.bos_token): <class 'NoneType'>
23:10:40-117121 INFO     type(shared.tokenizer.bos_token_id): <class 'NoneType'>
23:10:40-118359 INFO     type(shared.tokenizer.build_inputs_with_special_tokens): <class 'method'>
23:10:40-119123 INFO     type(shared.tokenizer.can_save_slow_tokenizer): <class 'bool'>
23:10:40-120123 INFO     type(shared.tokenizer.chat_template): <class 'str'>
23:10:40-121124 INFO     type(shared.tokenizer.clean_up_tokenization): <class 'function'>
23:10:40-121625 INFO     type(shared.tokenizer.clean_up_tokenization_spaces): <class 'bool'>
23:10:40-122625 INFO     type(shared.tokenizer.cls_token): <class 'NoneType'>
23:10:40-123126 INFO     type(shared.tokenizer.cls_token_id): <class 'NoneType'>
23:10:40-124127 INFO     type(shared.tokenizer.convert_added_tokens): <class 'method'>
23:10:40-125128 INFO     type(shared.tokenizer.convert_ids_to_tokens): <class 'method'>
23:10:40-125628 INFO     type(shared.tokenizer.convert_tokens_to_ids): <class 'method'>
23:10:40-126629 INFO     type(shared.tokenizer.convert_tokens_to_string): <class 'method'>
23:10:40-127630 INFO     type(shared.tokenizer.create_token_type_ids_from_sequences): <class 'method'>
23:10:40-128130 INFO     type(shared.tokenizer.decode): <class 'method'>
23:10:40-129131 INFO     type(shared.tokenizer.decoder): <class 'tokenizers.decoders.ByteLevel'>
23:10:40-130132 INFO     type(shared.tokenizer.default_chat_template): <class 'str'>
23:10:40-131133 INFO     type(shared.tokenizer.deprecation_warnings): <class 'dict'>
23:10:40-132134 INFO     type(shared.tokenizer.encode): <class 'method'>
23:10:40-133135 INFO     type(shared.tokenizer.encode_plus): <class 'method'>
23:10:40-133635 INFO     type(shared.tokenizer.eos_token): <class 'str'>
23:10:40-134635 INFO     type(shared.tokenizer.eos_token_id): <class 'int'>
23:10:40-135638 INFO     type(shared.tokenizer.from_pretrained): <class 'method'>
23:10:40-136137 INFO     type(shared.tokenizer.get_added_vocab): <class 'method'>
23:10:40-137138 INFO     type(shared.tokenizer.get_special_tokens_mask): <class 'method'>
23:10:40-138139 INFO     type(shared.tokenizer.get_vocab): <class 'method'>
23:10:40-138640 INFO     type(shared.tokenizer.init_inputs): <class 'tuple'>
23:10:40-139640 INFO     type(shared.tokenizer.init_kwargs): <class 'dict'>
23:10:40-140141 INFO     type(shared.tokenizer.is_fast): <class 'bool'>
23:10:40-141141 INFO     type(shared.tokenizer.mask_token): <class 'NoneType'>
23:10:40-141642 INFO     type(shared.tokenizer.mask_token_id): <class 'NoneType'>
23:10:40-142642 INFO     type(shared.tokenizer.max_len_sentences_pair): <class 'int'>
23:10:40-143644 INFO     type(shared.tokenizer.max_len_single_sentence): <class 'int'>
23:10:40-144644 INFO     type(shared.tokenizer.model_input_names): <class 'list'>
23:10:40-145145 INFO     type(shared.tokenizer.model_max_length): <class 'int'>
23:10:40-146146 INFO     type(shared.tokenizer.name_or_path): <class 'str'>
23:10:40-147147 INFO     type(shared.tokenizer.num_special_tokens_to_add): <class 'method'>
23:10:40-148147 INFO     type(shared.tokenizer.pad): <class 'method'>
23:10:40-149148 INFO     type(shared.tokenizer.pad_token): <class 'NoneType'>
23:10:40-149648 INFO     type(shared.tokenizer.pad_token_id): <class 'NoneType'>
23:10:40-150650 INFO     type(shared.tokenizer.pad_token_type_id): <class 'int'>
23:10:40-151650 INFO     type(shared.tokenizer.padding_side): <class 'str'>
23:10:40-152151 INFO     type(shared.tokenizer.prepare_for_model): <class 'method'>
23:10:40-153152 INFO     type(shared.tokenizer.prepare_seq2seq_batch): <class 'method'>
23:10:40-154152 INFO     type(shared.tokenizer.pretrained_vocab_files_map): <class 'dict'>
23:10:40-154653 INFO     type(shared.tokenizer.push_to_hub): <class 'method'>
23:10:40-155654 INFO     type(shared.tokenizer.register_for_auto_class): <class 'method'>
23:10:40-156655 INFO     type(shared.tokenizer.sanitize_special_tokens): <class 'method'>
23:10:40-157155 INFO     type(shared.tokenizer.save_pretrained): <class 'method'>
23:10:40-158156 INFO     type(shared.tokenizer.save_vocabulary): <class 'method'>
23:10:40-159157 INFO     type(shared.tokenizer.sep_token): <class 'NoneType'>
23:10:40-160158 INFO     type(shared.tokenizer.sep_token_id): <class 'NoneType'>
23:10:40-160658 INFO     type(shared.tokenizer.set_truncation_and_padding): <class 'method'>
23:10:40-161659 INFO     type(shared.tokenizer.slow_tokenizer_class): <class 'NoneType'>
23:10:40-162160 INFO     type(shared.tokenizer.special_tokens_map): <class 'dict'>
23:10:40-163160 INFO     type(shared.tokenizer.special_tokens_map_extended): <class 'dict'>
23:10:40-164662 INFO     type(shared.tokenizer.split_special_tokens): <class 'bool'>
23:10:40-165162 INFO     type(shared.tokenizer.tokenize): <class 'method'>
23:10:40-166164 INFO     type(shared.tokenizer.train_new_from_iterator): <class 'method'>
23:10:40-167164 INFO     type(shared.tokenizer.truncate_sequences): <class 'method'>
23:10:40-168164 INFO     type(shared.tokenizer.truncation_side): <class 'str'>
23:10:40-169165 INFO     type(shared.tokenizer.unk_token): <class 'NoneType'>
23:10:40-169666 INFO     type(shared.tokenizer.unk_token_id): <class 'NoneType'>
23:10:40-170666 INFO     type(shared.tokenizer.verbose): <class 'bool'>
23:10:40-193686 INFO     type(shared.tokenizer.vocab): <class 'dict'>
23:10:40-194688 INFO     type(shared.tokenizer.vocab_files_names): <class 'dict'>
23:10:40-195689 INFO     type(shared.tokenizer.vocab_size): <class 'int'>
23:10:40-196689 INFO     ===========================================================
```

**Pull request merged**
