### PR TITLE
[extensions/openai] Fixes for: embeddings, tokens, better errors. +Docs update, +Images, +logit_bias/logprobs, +more.

### LINKED ISSUE #3172: Support for 'repetition_penalty' in openai extension
**Description**

Hi, I'm using this wonderful project with Vicuna and Longchat model.

I do see the note of `repetition_penalty` says 'this seems to operate with a different scale and defaults, I tried to scale it based on range & defaults, but the results are terrible. hardcoded to 1.18 until there is a better way'. But based on my scenario on WebUI, I find some times `StarChat` parameters preset works better than other presets, which means `repetition_penalty` should be `1.0`.

So would you please add a line like
```python
req_params['repetition_penalty'] = default(body, 'repetition_penalty', req_params['repetition_penalty'])
```
in [extensions/openai/completions.py](https://github.com/oobabooga/text-generation-webui/blob/9f0803886451c9b6e817c8b3adbe1044e6856d6e/extensions/openai/completions.py) so the parameter can be tuned?

Thanks!

### PR DESCRIPTION
**Pull request by matatonic**
* Fixed: Embeddings were consuming VRAM even when it says it was loaded to CPU, set to CPU by default for the model and embeddings. +option to use GPU (OPENEDAI_EMBEDDING_MODEL_DEVICE=cuda)
* Embeddings were loaded on demand in the last release (Jul 12), so this will only impact users of embeddings and moderations.
* Docs update
* fix token count
* Better errors & better error handling
* fix tiktoken list input
* improve default chat instruction template
* experimental: logit_bias & logprobs
* Major images quality improvements
* hacks for presence_penalty/repetition_penalty improvements (Fixes #3172)
* Fixes: #3228

### CODE REVIEW

**Comment by matatonic** [comment]
All test passing as expected.

**Comment by matatonic** [comment]
All test passing as expected.

**Comment by matatonic** [comment]
All test passing as expected.

**Comment by matatonic** [comment]
@oobabooga This is ready for merge, it has some valuable fixes and improvements and has been tested by a few people already.

**Comment by oobabooga** [comment]
Thanks for the heads up @matatonic.

**Pull request merged**
