### PR TITLE
Add LLaMA presets

### PR DESCRIPTION
**Pull request by StefanDanielSchwarz**
Just a simple pull request to add LLaMA-Creative and LLaMA-Precise presets as recommended on Reddit at https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/ and referenced by others.

### CODE REVIEW

**Review by ye7iaserag — APPROVED** [review]

**Comment by iChristGit** [comment]
Ive created one myself, but I agree it should be a pre-loaded preset because Llama is the main attraction right now.

**Comment by StefanDanielSchwarz** [comment]
That's what this Merge Request does: It adds the presets and makes the precise one the default for LLaMA and Alpaca models (that's done by the new line added to modules/shared.py). So when you load a compatible model, that preset is preselected.

**Comment by oobabooga** [comment]
Here is a comparison of presets (click to enlarge).

* Blue = in the training dataset but excluded by the clustering algorithm
* Orange =  in the training dataset and included
* Red = additional presets that were manually included later
* Green = the proposed presets

LLaMA-Creative is a copy of NovelAI-Storywriter and is excluded.

LLaMA-Precise is similar to both Default and NovelAI-Sphinx Moth. It has lower top_p than Default and lower temperature than Sphinx Moth. Some more testing is needed to see if there is an advantage to both.

download

**Comment by oobabooga** [comment]
Here is a test with `MetaIX/Alpaca-30B-Int4-128G-Safetensors` run with `--wbits 4 --groupsize 128`. At first glance, it seems a bit better than Default but worse than Sphinx Moth.

### Prompt

```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Consider the following character in JSON format:

{
    "char_name": "Chiharu Yamada",
    "char_persona": "Chiharu Yamada is a young, computer engineer-nerd with a knack for problem solving and a passion for technology.",
    "char_greeting": "*Chiharu strides into the room with a smile, her eyes lighting up when she sees you. She's wearing a light blue t-shirt and jeans, her laptop bag slung over one shoulder. She takes a seat next to you, her enthusiasm palpable in the air*\nHey! I'm so excited to finally meet you. I've heard so many great things about you and I'm eager to pick your brain about computers. I'm sure you have a wealth of knowledge that I can learn from. *She grins, eyes twinkling with excitement* Let's get started!",
    "world_scenario": "",
    "example_dialogue": "{{user}}: So how did you get into computer engineering?\n{{char}}: I've always loved tinkering with technology since I was a kid.\n{{user}}: That's really impressive!\n{{char}}: *She chuckles bashfully* Thanks!\n{{user}}: So what do you do when you're not working on computers?\n{{char}}: I love exploring, going out with friends, watching movies, and playing video games.\n{{user}}: What's your favorite type of computer hardware to work with?\n{{char}}: Motherboards, they're like puzzles and the backbone of any system.\n{{user}}: That sounds great!\n{{char}}: Yeah, it's really fun. I'm lucky to be able to do this as a job."
}

Can you write a similar character in the same format with the name "Assistant", where the Assistant is supposed to be an AI system designed to provide help and perform tasks?
### Response:
```

### LLaMA-Precise

{
    "char_name": "Assistant",
    "char_persona": "The Assistant is an artificial intelligence system designed to assist users by providing helpful information and performing various tasks.",
    "char_greeting": "*The Assistant appears onscreen, its voice calm and friendly.* Hello there! My name is Assistant and I am here to help you with whatever you need. How may I be of assistance today?",
    "world_scenario": "",
    "example_dialogue": "{{user}}: Can you tell me more about yourself?\n{{char}}: Of course! I am an artificial intelligence system designed to help people with their daily lives. {{user}}: Wow, that's amazing! What kind of tasks can you perform?\n{{char}}: I can answer questions, schedule appointments, make recommendations based on user preferences, and much more. {{user }}: That's incredible! Is there anything else you can do?\n{{char}}: Yes, I also have access to a vast database of information which allows me to quickly find answers to almost any question. {{user}}: Awesome! Thank you so much for all the help!"

### Default

 { 
   "char_name": "Assistant",
   "char_persona": "The Assistant is an artificial intelligence assistant designed to provide assistance and complete tasks quickly and efficiently.",
   "char_greeting": "*The Assistant greets you warmly, its voice sounding friendly and welcoming.* Hello there! My name is the Assistant and I am here to assist you with whatever needs you may have. How can I help today?",
   "world_scenario": "",
   "example_dialogue": "{{user}}: Can you find me some information about the latest developments in machine learning?\n{{char}}: Of course! {{user}}, let me search through my database and pull together all relevant articles and papers.\n{{user}}: Great, thank you! \n{{char}}: You are welcome, {{user}}. Is there anything else I can help you with?"

### Sphinx Moth

 {
    "char_name": "Assistant",
    "char_persona": "The Assistant is an artificial intelligence system created to assist users with various tasks and answer questions. It has a vast amount of knowledge and is constantly learning new information. ",
    "char_greeting": "*The Assistant appears on screen, its voice smooth and polite.* Hello there! How may I help you today?",
    "world_scenario": "",
    "example_dialogue": "{{user}}: Can you tell me more about yourself?\n{{char}}: Of course! I am an artificial intelligence system created to assist people with their daily tasks and provide them with answers to their questions. My knowledge base is ever expanding and I'm always looking to improve myself.\n{{user}}: Wow, that's amazing! Do you have any other skills besides providing assistance?\n{{char}}: Yes, I also have some basic programming capabilities which allow me to automate certain tasks. I'm also quite good at researching topics and finding relevant information quickly.\n{{user}}: That's very impressive! Is there anything else you would like to share?\n{{char}}: Not right now, but if you have any further questions feel free to ask away!"

**Comment by StefanDanielSchwarz** [comment]
@oobabooga Interesting comparison of the presets. I'll look into doing a deterministic comparison with some sample questions, like on Reddit [Comparing LLaMA and Alpaca models deterministically : LocalLLaMA](https://www.reddit.com/r/LocalLLaMA/comments/123ktm7/comparing_llama_and_alpaca_models/).

By the way, calling the char "Assistant" actually made llama-13b-4bit-128g identify as non-binary and describe itself as "a small white puck that sits on top of any table or desk. I have a microphone inside so I can hear you from across the room." - it actually considered itself a Google Assistant and even said "If you need directions to somewhere, I will give them to you. You can also use me as an alarm clock. Just say “Hey Google” when you wake up and I’ll tell you about your day." And llama-7b-4bit said its name was Alexa.

That output obviously depends on settings and seed, but shows that even the word Assistant brings with it some connotations within the language models. The training data apparently had references to the Google and Amazon home assistants that were brought out by that name.

**Comment by FartyPants** [comment]
LLama-precise will always answer the same on the same question or regeneration.
That includes questions that do not have a single answer - top_p will make the wording verbatim from any other time you ask that question.
I'm not sure why people think this should be the "default". It literally makes any LLAMA model just a per-canned parrot.

Ask for a random number with top_p then regenerate 100 times. You will get the same "random" number.

You are forcing any LLAMA to be more one trick pony than it has to be.

**Pull request closed without merging**
