### PR TITLE
Lora Trainer improvements, part 6 - slightly better raw text inputs

### PR DESCRIPTION
**Pull request by mcmonkey4eva**
- Added an error check for if overlap/cutoff lengths don't make sense, that gives a clear error message (as a user on Discord was confused about it)
- Added `Hard Cut String`, a way to prevent unwanted overlaps.
This enables you to have text files like...
```
User: Question
Assistant: Answer


User: Question2
Assistant: Answer2
```
And it works just like a formatted json dataset wherein it properly cuts each chunk apart, but instead of messy json data you just split em with newlines. I made it generic enough that you can repurpose it to other split strings, other numbers of newlines, etc. easily within the UI.
Similarly useful if the raw text input is a series of different documents / quotes / whatever, separated by some consistent space block.
Prior to this change, models trained with this type of input would tend to learn that it's okay to suddenly and randomly change the subject (as, well, that's what the data did! And now, with this, your data doesn't, so theoretically your bot doesn't either).
I was originally going to use `ast` logic like `custom_stopping_strings` does but tbh I don't think it's worth the bother? You're unlikely to have multiple separator strings that need python-syntax input, so I just specialcased newlines and made it otherwise just a string.
- Also, added short bit of documentation about raw text file settings in the docs.
- ~~I was planning to test and implement the fix <https://github.com/oobabooga/text-generation-webui/discussions/1586> but I can't actually currently replicate the bug anymore ... and I do not not why. I also don't know why I was ever able to replicate the bug in the first place, as it's a strange bug that shouldn't happen. I might've updated packages at some point and that's why it's fine now? Not sure.~~ Confirmed as fixed by upstream
- I also wanted to look into multigpu training (per my jank housefire of a multigpu setup https://github.com/oobabooga/text-generation-webui/pull/2100 ) but, uh, frankly `torchrun` is an absolute nightmare, and pytorch internal splitting... exists, but is awful. And building my own multigpu logic as in that PR would be way more complicated, as it involves HF Transformers internals. So I'm not sure on how to do that, but it's a whole separate massive project.

### CODE REVIEW

**Comment by Ph0rk0z** [comment]
FYI.. since you're working on this.. is it possible to fix this error for steps under 100?

```
Exception in thread Thread-11 (threaded_run):
Traceback (most recent call last):
  File "/home/mint/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/mint/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mint/gptq2/text-generation-webui-testing/modules/training.py", line 416, in threaded_run
    trainer.train()
  File "/home/mint/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/mint/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 2066, in _inner_training_loop
    train_loss = self._total_loss_scalar / self.state.global_step
ZeroDivisionError: float division by zero

```

**Comment by mcmonkey4eva** [comment]
That'd be a reasonable idea. To my knowledge, there's nothing stopping that from being done within current code (assuming special tokens aren't stripped by default encode/decode calls)

**Comment by oobabooga** [comment]
Fair enough, thank you.

**Comment by Ph0rk0z** [comment]
Ok.. makes sense. Then it can't be fixed.

**Pull request merged**
