### PR TITLE
[extensions/openai] Add cross-origin headers, chunked responses, update [done] termination

### PR DESCRIPTION
**Pull request by oceanplexian**
## add cross-origin headers, chunked responses, update [done] termination
I was trying to get this to work with Anse (https://github.com/anse-app/anse), and ran into a few things. 
- Some apps expect XSS headers, added some for now
- HTTP expects chunks to have hexidecimal representation of the chunk size and a few \r\n's, or browers get upset. They now look like this after troubleshooting it with a packet capture:
```
    ##
    T 10.10.0.129:5001 -> 10.10.0.129:42088 [AP] #1628
    f3.
    data: {"id": "chatcmpl-1685337986", "object": "chat.completions.chunk", "created": 1685337986, "model": "WizardLM- 
    30B-Uncensored-GPTQ", "choices": [{"index": 0, "finish_reason": null, "message": {"content": "."}, "delta": {"content": 
    "."}}]}.
    .
    .

    ##
```

- My model  doesn't have a system prompt, which causes a crash, added a fix
- The [done] message contained two data blocks which crashed javascript parser. Removed the empty data, seems like the API consumer expects [done] and nothing else. 

## Testing:

**Logs:**
```
INFO:Loading the extension "openai"...
Running on local URL:  http://0.0.0.0:6001

To create a public link, set `share=True` in `launch()`.

Loaded embedding model: all-mpnet-base-v2, max sequence length: 384
Starting OpenAI compatible api:
OPENAI_API_BASE=http://0.0.0.0:5001/v1
10.10.0.129 - - [29/May/2023 05:25:41] "POST /v1/chat/completions HTTP/1.1" 200 -
Output generated in 4.23 seconds (2.37 tokens/s, 10 tokens, context 10, seed 783780625)
10.10.0.129 - - [29/May/2023 05:25:48] "POST /v1/chat/completions HTTP/1.1" 200 -
Output generated in 2.99 seconds (2.34 tokens/s, 7 tokens, context 30, seed 1622019454)
10.10.0.129 - - [29/May/2023 05:25:55] "POST /v1/chat/completions HTTP/1.1" 200 -
Output generated in 3.28 seconds (3.96 tokens/s, 13 tokens, context 47, seed 1263856111)
```
**Anse output:**
Screenshot 2023-05-28 at 11 44 45 PM

### CODE REVIEW

**Comment by matatonic** [comment]
That's a big change, wow, I'm looking over this now. Are the \r's really necessary??

BTW, the empty system prompt was fixed in: https://github.com/oobabooga/text-generation-webui/pull/2383

**Comment by matatonic** [comment]
@oceanplexian 
This is awesome, I hope you don't mind but I reworked your changes a bit (removed some bits, changed some bits) and included them in another PR (https://github.com/oobabooga/text-generation-webui/pull/2423)

If you could confirm my changes still work for you that would be much appreciated.

**Comment by matatonic** [comment]
anse is really cool, even the images endpoint works with my sad hack of a data:base64 encoded url for an image file.

**Comment by matatonic** [comment]
This does fix the issue with other Node.js apps (chatgpt-web at least, which also uses the openai-node code)! Thanks again.

**Comment by oobabooga** [comment]
I merged https://github.com/oobabooga/text-generation-webui/pull/2423, which if I understand correctly has the same functionality as this one, so I'll close it. Thanks for the contribution @oceanplexian and feel free to submit more PRs in the future.

**Pull request closed without merging**
