### PR TITLE
Extension: KoboldAI api

### PR DESCRIPTION
**Pull request by mayaeary**
Extension for some minimal set of KoboldAI-like api. 

Intended to be used with tools like TavernAI frontend.

### CODE REVIEW

**Comment by oobabooga** [comment]
I have just tested it with TavernAI and it worked perfectly. Very nice!

For reference, I started the web UI with

```
python server.py --no-stream --model llama-7b --extensions api
```

and set the API URL to

```
http://127.0.0.1:5000/api
```

**Comment by oobabooga** [comment]
Added to the wiki https://github.com/oobabooga/text-generation-webui/wiki/Extensions#gallery

**Comment by rabidcopy** [comment]
Any chance of this being made to work in conjunction with --share/gradio links when using Colab?

**Comment by oobabooga** [comment]
@rabidcopy see the PR above

**Comment by rabidcopy** [comment]
Ah, very nice! Thank you!

**Comment by hpnyaggerman** [comment]
Getting this with TavernAI:
```127.0.0.1 - - [19/Mar/2023 12:46:30] "GET /api/v1/model HTTP/1.1" 200 -
127.0.0.1 - - [19/Mar/2023 12:46:31] "POST /api/v1/generate HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 51894)
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\ProgramData\miniconda3\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\ProgramData\miniconda3\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\ProgramData\miniconda3\lib\http\server.py", line 433, in handle
    self.handle_one_request()
  File "C:\ProgramData\miniconda3\lib\http\server.py", line 421, in handle_one_request
    method()
  File "D:\oobabooga\text-generation-webui\extensions\api\script.py", line 43, in do_POST
    generator = generate_reply(
TypeError: generate_reply() got an unexpected keyword argument 'encoder_repetition_penalty'
----------------------------------------```

**Comment by hpnyaggerman** [comment]
> Getting this with TavernAI:
> 
> ```
> 127.0.0.1 - - [19/Mar/2023 12:46:31] "POST /api/v1/generate HTTP/1.1" 200 -
> ----------------------------------------
> Exception occurred during processing of request from ('127.0.0.1', 51894)
> Traceback (most recent call last):
>   File "C:\ProgramData\miniconda3\lib\socketserver.py", line 683, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\ProgramData\miniconda3\lib\socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\ProgramData\miniconda3\lib\socketserver.py", line 747, in __init__
>     self.handle()
>   File "C:\ProgramData\miniconda3\lib\http\server.py", line 433, in handle
>     self.handle_one_request()
>   File "C:\ProgramData\miniconda3\lib\http\server.py", line 421, in handle_one_request
>     method()
>   File "D:\oobabooga\text-generation-webui\extensions\api\script.py", line 43, in do_POST
>     generator = generate_reply(
> TypeError: generate_reply() got an unexpected keyword argument 'encoder_repetition_penalty'
> ----------------------------------------
> ```

Reviewed, seems like I am just using an outdated version of text-generation-webgui, going to leave the reply up for people with a similar problem

**Pull request merged**
