### PR TITLE
Deepl translate extensions

### PR DESCRIPTION
**Pull request by SnowMasaya**
## Checklist:

- [ ] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by Touch-Night** [comment]
As a rule of thumb, new extensions should be submitted to https://github.com/oobabooga/text-generation-webui-extensions. You are highly encouraged to submit your extensions to that list!

New built-in extensions can be accepted in cases where they would be useful to a large percentage of the user base, preferably while adding few or no additional dependencies.

**Comment by SnowMasaya** [comment]
Thanks. I made pull requests

- https://github.com/SnowMasaya/text-generation-webui-extensions/pull/1

**Comment by SnowMasaya** [comment]
Thanks. I made pull request

- https://github.com/oobabooga/text-generation-webui-extensions/pull/30

**Comment by oobabooga** [comment]
Accepted on https://github.com/oobabooga/text-generation-webui-extensions

**Pull request closed without merging**
