### PR TITLE
Bump llama-cpp-python to 0.1.84

### PR DESCRIPTION
**Pull request by jllllll**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).
---
https://github.com/abetlen/llama-cpp-python/compare/v0.1.83...v0.1.84
https://github.com/ggerganov/llama.cpp/compare/06abf8eebabe086ca4003dee2754ab45032cd3fd...21ac3a1503001020122db5dce6adf34b761675f5

### CODE REVIEW

**Comment by Ph0rk0z** [comment]
They also added beam search?

**Comment by jllllll** [comment]
I think they already had it. The code for it just got moved around in llama-cpp-python 0.1.84.

**Comment by Ph0rk0z** [comment]
Is beam search added to llama.cpp loader? I thought it's not there.

**Comment by jllllll** [comment]
I don't think it is implemented in the webui for this loader, but it is available in llama.cpp.

**Pull request merged**
