### PR TITLE
Broaden GPTQ-for-LLaMA branch support

### PR DESCRIPTION
**Pull request by EyeDeck**
Conditionalized the keyword arguments passed to GPTQ-for-LLaMA's `quant.make_quant()` so we can support more branches simultaneously. Pretty simple, we just test which kwargs `quant.make_quant()` currently has available and don't try to send any invalid ones.

Tested (with varying launch.py arguments) on:
* Oobabooga's old CUDA fork: [9659310499cc7a0ea5498c1beb47bb228d65d178](https://github.com/oobabooga/GPTQ-for-LLaMa/tree/9659310499cc7a0ea5498c1beb47bb228d65d178)
* Current CUDA branch: [610fdae6588c2b17bcf2726cacaaf795cd45077e](https://github.com/qwopqwop200/GPTQ-for-LLaMa/tree/610fdae6588c2b17bcf2726cacaaf795cd45077e)
* Current triton branch: [6800a08c7a3d8d682499df5d6d96666253af8ed1](https://github.com/qwopqwop200/GPTQ-for-LLaMa/tree/6800a08c7a3d8d682499df5d6d96666253af8ed1)

I suspect it would also work with the older non-groupsize versions too, but I don't think I have any old quantizations lying around to test it.

Following up #785

Just to be clear, this still won't make a model quantized by an excessively different version of GPTQ-for-LLaMA load, so e.g. you still need the old CUDA GPTQ-for-LLaMA in your repositories directory to use the 2-week-oldish quantizations most users probably have at this point. Likewise, if you want to try the new triton branch, you'll need to grab some fresh requantizations.
This PR is just so you can use different GPTQ-for-LLaMA versions without having to _also_ fiddle with text-generation-webui code to get things cooperating.

### CODE REVIEW

**Comment by EyeDeck** [comment]
By the way I've now gotten a chance to test performance at different context sizes of the new triton branch (via WSL2), with a fresh quantization, following up https://github.com/oobabooga/text-generation-webui/issues/734#issuecomment-1496928371 
* Upstream triton branch; LLaMA 30B --wbits 4 --act-order --true-sequential --groupsize 128
* > Output generated in 8.69 seconds (4.72 tokens/s, 41 tokens, context 696)
Output generated in 35.14 seconds (5.66 tokens/s, 199 tokens, context 738)
Output generated in 36.51 seconds (5.45 tokens/s, 199 tokens, context 937)
Output generated in 38.51 seconds (5.17 tokens/s, 199 tokens, context 1137)
Output generated in 41.56 seconds (4.79 tokens/s, 199 tokens, context 1336)
Output generated in 39.90 seconds (4.99 tokens/s, 199 tokens, context 1535)
Output generated in 44.05 seconds (4.52 tokens/s, 199 tokens, context 1734)
Output generated in 45.22 seconds (4.40 tokens/s, 199 tokens, context 1848)
Output generated in 33.63 seconds (5.92 tokens/s, 199 tokens, context 23)

On this machine (single 3090), the triton branch is around 80% as fast as old cuda branch at large context size, which isn't too bad considering the new cuda branch is around 1.27% as fast as the old cuda branch. Also, I seem to be able to do 1848 context size with `--groupsize 128` and not OOM, while the old branch + `--groupsize 128` usually OOMed after roughly 1650.

If you're willing to take about a 20% speed hit, I'm sure the improved model quality achieved by act-order + groupsize is very nice.

**Comment by Ph0rk0z** [comment]
Heh.. its a 20% speed hit on almost the top consumer GPU. Wonder if it will run at all on mine and what the hit will be.

Why not go all the way and support v1, v2 and is it now v3 models? Just use separate GPTQ loaders and a command line parameter.

**Comment by oobabooga** [comment]
Very nice! As a sanity check, I have tested it with my current models and they loaded without errors and had the same text generation performance.

I thought the triton branch was slower. 80% is not bad at all, considering that the CUDA branch is already several times faster than running the model in 16-bit mode using the default transformers code.

**Comment by BadisG** [comment]
So on the repository folder I have to create 2 GPTQ-for-LLaMA?
Something like:  
GPTQ-for-LLaMA-CUDA
GPTQ-for-LLaMA-TRITON

But I have a different cuda environnement for both Cuda and Triton... if you can help me clarify stuff I would be grateful

**Comment by BadisG** [comment]
How can you clone differents GPTQ-for-LLaMa folders if they have the same names? And like I said I have a different conda environnement for both cuda and triton, do you mean I can do it with just one env?

**Comment by oobabooga** [comment]
You can't, you have to delete/rename the existing folder and clone/install a new one. I'm not saying this is ideal, it's just that adding support for multiple GPTQ-for-LLaMa folders at the same time is beyond the scope of this PR

**Comment by EyeDeck** [comment]
Well, there are a couple of different obstacles to having different setups of GPTQ-for-LLaMA to seamlessly switch between:
* As far as I know, there still isn't any explicit metadata stored with the actual quantized model that tells which version can load it; it might be possible to deduce via the internal layer names (which changed a couple of times), or even just try trial-and-error
* More of a problem, all the CUDA versions of GPTQ-for-LLaMA require slightly different custom CUDA kernels, which replace each other; so it would be necessary to:
* * execute GPTQ-for-LLaMA's setup_cuda.py every time the webui switches,
* * or track down old GPTQ-for-LLaMA commits, patch them so they can coexist without conflicting, and then get users to use those patched old versions instead of qwopqwop200's official versions

It _is_ a bit silly how quantized models don't have any standardized metadata to read. Making the user have to manually handle version + wbits + groupsize feels clumsy. _But_, the GPTQ-for-LLaMA is still only a month old as of today, so this is all still very early development.

**Comment by oobabooga** [comment]
The models have versioning because past versions were never supposed to be re-utilized. For instance, hugging face has recently changed the LLaMA tokenizer format requiring a new conversion. The old files are obsolete and to be deleted. But in the case of GPTQ-for-LLaMA, a trade off appeared between the past and current versions.

In any case, wbits and groupsize should indeed be saved in a metadata file.

**Pull request merged**
