### PR TITLE
Implement a demo HF wrapper for exllama to utilize existing HF transformers decoding.

### PR DESCRIPTION
**Pull request by Larryvrh**
This reuse of HF decoding makes the generation result from exllama more "aligned" with the original gptq outputs. This implementation is just a demo version and may need more work to increase the compatibility in all aspects.

### CODE REVIEW

**Comment by oobabooga** [comment]
That's amazing! I'd like to offer you a trophy: 🏆

This is what I found after some testing:

1) It works.
2) Performance is about 11% slower - from 28 tokens/s to 25 tokens/s for a 30b model on a RTX 3090. I think that this is acceptable given how much more samplers become available.
3) For some reason, loading TheBloke/WizardLM-30B-GPTQ works, but loading llama-30b-4bit-128g or llama-7b-4bit-128g hangs.
4) Contrastive Search doesn't work.

It would be nice if someone could test it on a multi-gpu setup.

**Comment by Ph0rk0z** [comment]
For these settings, I looked in model.py:
```

        self.groupsize = None  # Autodetected
        self.act_order = False  # Autodetected
        self.empty_g_idx = False  # Autodetected
```

So not sure if act_order should be set true. FusedMLP/Fusedattention can be freely set though.

**Comment by Panchovix** [comment]
Just to add



> 3\. For some reason, loading TheBloke/WizardLM-30B-GPTQ works, but loading llama-30b-4bit-128g or llama-7b-4bit-128g hangs.

I can see that some models get stuck and not load. It seems to be related to protobuf? I got a gigantic error on trying to load https://huggingface.co/BGLuck/h2ogpt-research-oasst1-llama-65b-4bit after either downgrading protobuf to 3.20 (which it asked me to downgrade from 4.23) or setting 'PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION="python"'

The first error is

```
2023-06-22 03:26:07 INFO:Loading h2oai_h2ogpt-research-oasst1-llama-65b-4bit...
2023-06-22 03:26:21 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\server.py", line 62, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 74, in load_model
    tokenizer = load_tokenizer(model_name, model)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 109, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code)
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 691, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\models\llama\tokenization_llama_fast.py", line 93, in __init__
    super().__init__(
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\convert_slow_tokenizer.py", line 1307, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\convert_slow_tokenizer.py", line 445, in __init__
    from .utils import sentencepiece_model_pb2 as model_pb2
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\utils\sentencepiece_model_pb2.py", line 91, in <module>
    _descriptor.EnumValueDescriptor(
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\google\protobuf\descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

Then, after applying either of the 2 fixes mentioned above, I get

`Traceback (most recent call last): File “F:\ChatIAs\oobabooga\text-generation-webui\[server.py](http://server.py/)”, line 62, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “F:\ChatIAs\oobabooga\text-generation-webui\modules\[models.py](http://models.py/)”, line 74, in load_model tokenizer = load_tokenizer(model_name, model) File “F:\ChatIAs\oobabooga\text-generation-webui\modules\[models.py](http://models.py/)”, line 109, in load_tokenizer tokenizer = AutoTokenizer.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code) File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py”, line 691, in from_pretrained return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_base.py”, line 1825, in from_pretrained return cls._from_pretrained( File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_base.py”, line 1988, in _from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\models\llama\tokenization_llama_fast.py”, line 104, in init self.update_post_processor() File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\models\llama\tokenization_llama_fast.py”, line 111, in update_post_processor bos_token_id = self.bos_token_id File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_base.py”, line 1136, in bos_token_id return self.convert_tokens_to_ids(self.bos_token) File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_fast.py”, line 250, in convert_tokens_to_ids return self._convert_token_to_id_with_added_voc(tokens) File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_fast.py”, line 257, in _convert_token_to_id_with_added_voc return self.unk_token_id File “F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_base.py”, line 1155, in unk_token_id return self.convert_tokens_to_ids(self.unk_token) File “F:\ChatIAs\oobabooga\venv\lib\site-`

and repeat itself until 

```
File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1155, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
RecursionError: maximum recursion depth exceeded
```

Airoboros 65B works for example.

**Comment by Panchovix** [comment]
From what I'm testing, it doesn't work

[Llama-65B-32g](https://huggingface.co/Neko-Institute-of-Science/LLaMA-65B-4bit-32g)
[h2ogpt-research-oasst1-llama-65b-4bit](https://huggingface.co/BGLuck/h2ogpt-research-oasst1-llama-65b-4bit)
[alpaca-lora-65B-GPTQ-4bit](https://huggingface.co/TheBloke/alpaca-lora-65B-GPTQ-4bit)

**Comment by BadisG** [comment]
> I can see that some models get stuck and not load.
For me, the models doesn't load anymore, I tried exllama and exllama_hf and I have the same results

**Pull request merged**
