### PR TITLE
Show the total number of tokens and generation speed in chat UI (#2243)

### PR DESCRIPTION
**Pull request by kha84**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

## What's been done:

Two small changes:
1) one to  [modules/text_generation.py](https://github.com/oobabooga/text-generation-webui/pull/5357/files#diff-36dfef7d9db97b2cde9351ae9eafa7aed3dd15e094d2ca7a4a60bfa88d6096f2) to expose the number of tokens that was identified as "context" and "generated output" as per last call of generate_reply_HF / generate_reply_custom
2) another is to [modules/ui_chat.py](https://github.com/oobabooga/text-generation-webui/pull/5357/files#diff-ba9fb0480e9653459faabb353f96234192cb4d535a7143da3e4aaca5000eb51f) to show that number of tokens similar way how it's being shown for "Default" tab

### CODE REVIEW

**Comment by kha84** [comment]
image

**Comment by kha84** [comment]
Added token per second to be displayed, still WIP
Screenshot from 2024-01-29 00-01-49

**Comment by kha84** [comment]
Need to polish Gradio part - don't like the place, where it is being displayed currently.

**Comment by YakuzaSuske** [comment]
Why tho? It's already being displayed on the cmd window. Adding it to the UI would be unnecessary unless you using it through the API in which case it would helpful. But other than that, i don't see why people would want to know the speed and tokens if they are just interested in the output text itself.
image

However if you are determine to add it, i think the best placement would be somewhere here. The current placement is in the way of the user's vision and it might impede on the text they want to read.

**Comment by kha84** [comment]
Yeah, I was thinking about that placement as well, thanks!

Answering your "why" question:

1) having this crucial info hidden somewhere in logs doesn't seem to be very handy. In order to see these figures you need to jump back and forth between web ui and cli.

2) the amount of context used is quite important runtime parameter, even for chat-only casual users. For now you have to blind-guess if your chats are already out of the context window or not yet. Or to jump to CLI to see logs. Having it exposed to be displayed all the time gives you much more details about whether or not you should be still expecting coherent answers from your model.

**Comment by YakuzaSuske** [comment]
I think for me in my case it just seems kind of odd but.... tbh i always have the command window open and to the side. So i guess that's why i asked the question. I thought people always did that too but 🤷‍♂️  I guess i'm the only one who does that, so that's why i found it particularly odd since i can always at all times see the log, tokens a second, context, etc. by just glancing to my left real quick.

As seen below:
image

**Comment by biship** [comment]
Why not put it under or next to the {{char}} icon like SillyTavern does?

number of tokens and duration.

I think this is a good addition to the UI as I don't have the command window showing.

**Comment by bartowski1182** [comment]
@YakuzaSuske not everyone interacts on the same computer it's running on, I also use it on my phone, sometimes I'm curious and I'd rather not open terminal, ssh, find the program, watch the logs, and then swap between programs

I think this is a great inclusion and would love to see it implemented

**Comment by FartyPants** [comment]
> @YakuzaSuske not everyone interacts on the same computer it's running on, I also use it on my phone, sometimes I'm curious and I'd rather not open terminal, ssh, find the program, watch the logs, and then swap between programs
> 
> I think this is a great inclusion and would love to see it implemented

This is the correct answer for "why". There are many instances (remote access, runpod) where you don't always get to see terminal.

**Comment by oobabooga** [comment]
I find it cumbersome to see this kind of logs in the UI, while in the terminal the logs appear all on top of each other nicely.

**Comment by kha84** [comment]
Sure, you're the boss. Myself I switched to ollama + Open Web UI = it has this info printed in UI out-of-the-box

**Pull request closed without merging**
