### PR TITLE
move streaming API to existing extension api

### PR DESCRIPTION
**Pull request by Originalimoc**
Implementation follows within 1 hour

### CODE REVIEW

**Comment by oobabooga** [comment]
Duplicate of https://github.com/oobabooga/text-generation-webui/pull/990?

**Comment by Originalimoc** [comment]
😂Coincident. I'll provide the full updated code anyway, you choose which is better.

**Comment by Originalimoc** [comment]
commit 3850f13624fed5a002da14a2b2e3be95f59ca160 just now is the reason why I don't feel like using /queue/join, so this simpler approach should be better for compatibility for building downstream applications.

**Review by Originalimoc — COMMENTED** [review]
... or GitHub Desktop

**Comment by Originalimoc** [comment]
Done

**Comment by oobabooga** [comment]
Closing this in favor of https://github.com/oobabooga/text-generation-webui/pull/990, but thanks @Originalimoc for the PR.

**Pull request closed without merging**
