### PR TITLE
fix: broken builds, upgrade image to cuda 12.2

### LINKED ISSUE #4176: docker compose no module name 'torch'
### Describe the bug

Ubuntu 22.04 LTS
After running docker compose up --build 

got

  × python setup.py egg_info did not run successfully.
#9 11.09   │ exit code: 1
#9 11.09   ╰─> [6 lines of output]
#9 11.09       Traceback (most recent call last):
#9 11.09         File "<string>", line 2, in <module>
#9 11.09         File "<pip-setuptools-caller>", line 34, in <module>
#9 11.09         File "/tmp/pip-install-g3b1gyct/xformers_ece11b88871a456581ec13672a75669e/setup.py", line 18, in <module>
#9 11.09           import torch
#9 11.09       ModuleNotFoundError: No module named 'torch'
#9 11.09       [end of output]

Any help appreciated.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

docker compose up --build

### Screenshot

_No response_

### Logs

```shell
× python setup.py egg_info did not run successfully.
#9 11.09   │ exit code: 1
#9 11.09   ╰─> [6 lines of output]
#9 11.09       Traceback (most recent call last):
#9 11.09         File "<string>", line 2, in <module>
#9 11.09         File "<pip-setuptools-caller>", line 34, in <module>
#9 11.09         File "/tmp/pip-install-g3b1gyct/xformers_ece11b88871a456581ec13672a75669e/setup.py", line 18, in <module>
#9 11.09           import torch
#9 11.09       ModuleNotFoundError: No module named 'torch'
#9 11.09       [end of output]
```

### System Info

```shell
Ubuntu 22.04 LTS
```

### PR DESCRIPTION
**Pull request by sammcj**
Fixes #4176 

- Upgrade container base image to cuda 12.2

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by oobabooga** [comment]
Can you change it for the 11.8 command? The current wheels are all for CUDA 11.8.

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by sammcj** [comment]
Yeah sure, I’ll give it a go with the 12.2 image and 11.8 pip packages shortly.

**Comment by sammcj** [comment]
Out of interest is there any reason the other packages aren’t updated to 12? I did an all 12 build a while back that seemed to work well.

**Comment by oobabooga** [comment]
The recommended install command for 12.1 doesn't pin a version (pip3 install torch torchvision torchaudio), so I picked 11.8 for better stability. 12.1 also doesn't work for older GPUs, but it may be necessary to update due to flash attention support on windows

https://github.com/oobabooga/text-generation-webui/pull/4235

**Comment by sammcj** [comment]
Just had a crack at it, but it's the old 11.8 packages that are causing the issues 😞.

I had a look at at adding some logic in the Dockerfile to handle 12.x but it got messy - fast.

IMO it would be worth updating the project to CUDA 12 + Python 3.11 (or even 3.12?) as I've had quite a few issues with Torch on 11.8 on other projects recently, it's getting pretty long in the tooth I guess.

**Pull request closed without merging**
