### PR TITLE
Better error message when using OpenAI extension, but forgetting to load a model

### PR DESCRIPTION
**Pull request by uogbuji**
re: https://github.com/oobabooga/text-generation-webui/issues/2505

Being perfectly honest, not actually tested yet.

### CODE REVIEW

**Comment by LoopControl** [comment]
Tested this pull. The error message "No model has been loaded" which is much clearer than before:

```
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 58216)
Traceback (most recent call last):
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/mnt/ai/text-generation-webui/extensions/openai/script.py", line 232, in do_POST
    raise RuntimeError('No model has been loaded')
RuntimeError: No model has been loaded
----------------------------------------
```

However, on the client side, the server closes the connection without any response (it's usually best practice to return a HTTP 500 (Internal server error) or a HTTP 400 (Bad request error)

**Comment by uogbuji** [comment]
> However, on the client side, the server closes the connection without any response (it's usually best practice to return a HTTP 500 (Internal server error) or a HTTP 400 (Bad request error)

Yes. Good point. My PR was meant to be a quick & dirty since @matatonic was already looking more broadly into error handling. The good news is that I think they now have a PR that does the trick.

@matatonic I should close this, yes?

**Comment by uogbuji** [comment]
I'll just also say that most web frameworks I've used will by default automatically send back a 500 in case of an unhandled exception. I haven't used `BaseHTTPRequestHandler` in many years, but I'm surprised it doesn't.

**Comment by matatonic** [comment]
Yeah, I need to still wrap it more generally it to improve unknown errors, but yes, you can close this.

**Pull request closed without merging**
