### PR TITLE
Get SD samplers from API

### PR DESCRIPTION
**Pull request by missionfloyd**
Turns the sampler textbox into a dropdown populated with samplers from the API. Default is still DDIM.
image

### CODE REVIEW

**Comment by oobabooga** [comment]
Nice change, thanks! I think that the DDIM default is probably kind of outdated. What is a good but conservative sampler choice to use as a default instead? Any ideas @missionfloyd @GuizzyQC?

**Comment by GuizzyQC** [comment]
@oobabooga @missionfloyd I'm partial to DPM++ SDE Karras but I looked quickly at popular images on a popular Discord for sharing generated images and DPM++ 2M Karras is also popular.

**Comment by oobabooga** [comment]
Is any of these faster than the other?

**Comment by GuizzyQC** [comment]
DPM++ 2M Karras is significantly faster

**Comment by oobabooga** [comment]
I have made a quick test and DPM++ SDE Karras did seem to be a bit better, and indeed it is quite slower than DPM++ 2M Karras. I changed the default to DPM++ 2M Karras here https://github.com/oobabooga/text-generation-webui/commit/67a83f3ad9361c078ebcafa9c2c97ab9708f2fcb, it should be better than DDIM at least

**Pull request merged**
