### PR TITLE
fix: typo in yield statement

### PR DESCRIPTION
**Pull request by CharlesCNorton**
Corrected a typo in the yield statement by removing the extra "the" in the message "Please close the the web UI completely and launch it again to be able to load it."

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by Touch-Night** [comment]
I remember there's more typo when I'm making the Chinese translation of TGWUI, not only in the code, also wiki and docs. Can you fix all of that at one time?

**Comment by CharlesCNorton** [comment]
> I remember there's more typo when I'm making the Chinese translation of TGWUI, not only in the code, also wiki and docs. Can you fix all of that at one time?

Will do!

**Comment by oobabooga** [comment]
I second @Touch-Night, reviewing the codebase for simple English typos would be nice.

**Comment by CharlesCNorton** [comment]
Consider it done. I am going through the codebase as we speak and will open pull requests periodically.

**Comment by CharlesCNorton** [comment]
> I second @Touch-Night, reviewing the codebase for simple English typos would be nice.


Consider it done. I am going through the codebase as we speak and will open pull requests periodically.

**Comment by Touch-Night** [comment]
https://github.com/oobabooga/text-generation-webui/blob/4820ae9aef3b7716cb00a6519955db435b6dcb56/docs/02%20-%20Default%20and%20Notebook%20Tabs.md?plain=1#L21  
~Four~ -> Five

**Comment by CharlesCNorton** [comment]
> https://github.com/oobabooga/text-generation-webui/blob/4820ae9aef3b7716cb00a6519955db435b6dcb56/docs/02%20-%20Default%20and%20Notebook%20Tabs.md?plain=1#L21
> 
> 
> ~Four~ -> Five

Pull request created 👍

**Comment by oobabooga** [comment]
Could you create a single PR with all typo fixes?

**Comment by CharlesCNorton** [comment]
Done: https://github.com/oobabooga/text-generation-webui/pull/6151

**Comment by CharlesCNorton** [comment]
> Could you create a single PR with all typo fixes?

Done: https://github.com/oobabooga/text-generation-webui/pull/6151

**Comment by oobabooga** [comment]
I'm closing this one now that https://github.com/oobabooga/text-generation-webui/pull/6151 is merged.

**Pull request closed without merging**
