### PR TITLE
[extensions/openai]: Major openai extension updates & fixes

### PR DESCRIPTION
**Pull request by matatonic**
Major reorg of the code, updates & fixes in many areas.
* Handle context length problems correctly in Openai API
* Much improved error handling in Openai API
* Initial support for token array input (used by autogpt,langchain and some others)
* Remove obsolete stopping strings implementation
* Use custom_stopping_strings again
* Enable Moderation end point
* Improve system role messages
* chat top_k default (20) - curious how this works for others.
* Initial logit_bias and logprobs support for guidance (thanks to @cyberfox ) - not active yet, depends on https://github.com/oobabooga/text-generation-webui/pull/3029 for functionality
* major code cleanup & reorg. 
* Replaces https://github.com/oobabooga/text-generation-webui/pull/2942 openai updates.

Full testing is passing again (tokenizer fixups & merges.txt on my end cleaned up fixed up all new errors).

### CODE REVIEW

**Comment by matatonic** [comment]
I wish I could say it was better tested, but it looks like the tokenizer changes may have broken enough that my test suite is only partly functional. Not sure how to fix that yet.

**Comment by matatonic** [comment]
@oobabooga Testing is passing again and I think this is ready to merge.

**Comment by oobabooga** [comment]
Thanks for the fixes @matatonic

**Comment by matatonic** [comment]
> Is this merge supposed to solve longer context, ntk rope scaling etc?

Some related bugs were fixed, yes - can you elaborate a bit more? Are you experiencing any issues after the latest update?

**Comment by atisharma** [comment]
Before and after the update I am unable to send messages with context length > 2000, for cases where I can use full 8k context in the web ui. I've tried setting `truncation_length` as an API parameter. If this is not already known then I'll open a new issue with an example case (probably over the w/e).

**Comment by matatonic** [comment]
This is a known problem, but yes, please go ahead and open a bug. The UI does not set the truncation length on the server. To work around this for now, you can configure your models/config-user.yaml to include a line setting the truncation length for the model (or a pattern). 

For example:
.*superhot-8k:
  truncation_length: 8192

**Pull request merged**
