### PR TITLE
Add multi-user supports

### PR DESCRIPTION
**Pull request by HyeongminMoon**
This PR is a **[experimental]draft** for one server, multi-user support. 
Related to #58 .

### Behavior before PR:
Although this project is implemented using gradio's Blocks, but is not independently identified due to `shared` module.
Due to `shared` module, the app remembers all parameters, only works for single users.

### Behavior after PR:
Added `--multi_user` argument to apply multi history.
Each time we access or reload the url, a random uuid is generated, and multi history is managed by uuid as the key.
It's implemented as `shared.multi_history[UUID]`.
For now it only works with `--chat` mode

### Example usuage
```
python server.py --chat --multi_user [--multi_cnt 10]
```

### Challenge:
- [X] add multi-user history, multi-stop
- [X] A lot of functions have yet to be tested. Your help is needed to test and modify various function buttons on the chat interface. -> **Please test and report bugs!**
- [X] Changes in the `shared.history`, the project's core, caused many errors. Therefore, we might need to resolve possible bugs arising from this draft pull request. -> **Instead of changing history, added multi_history**
- [X] In draft implementation, uuid is created randomly upon page refresh (history is also cleared). To have a persistent history per user, we can link it with client_ip or gradio_auth. I'm not sure what is best[random, link to ip, link to gradio auth]. Any opinion or suggestion on this would be appreciated. -> **For now, random**
- [X] Furthermore, it is not desirable for a user's behavior (changing the settings, pressing the stop button, etc.) to affect other users. In order to avoid this, when using the `--multi_user` flag, the settings should be hidden, and events from triggering a function such as the stop button must be stored uniquely for each user by utilizing, for example, `shared.{object}[uuid]`. -> **refer multi-user variables in shared module**
- [x] While a user is using chatbot, other users can't use the chatbot due to Generation Lock. It would be best if we could implement batched inference, but I am thinking of adding a Pending message "waiting..." because the implementation is difficult at this point. -> **added multi_cnt argument and make it as Generation Semaphore limit. Now batched inference is working!😀**

Now ready.

### CODE REVIEW

**Comment by HyeongminMoon** [comment]
According to https://github.com/oobabooga/text-generation-webui/pull/2262, there is generation(concurrency) Lock in the text generation module.

I think it would be good in a situation where resources are scarce, but it seems more suitable for multi_user module to do batched inference if possible.

So now I suggest to remove it again because we can control it with `gradio.interface.queue(concurrency_count=multi_cnt)`.

**Comment by eu09** [comment]
@HyeongminMoon I folk from your repo , I have a question about using postman to call 
http://127.0.0.1:5000/api/v1/chat/
{
        "user_input": "user_input",
        "history": "007d0b3a-a6a1-4c7e-a223-eb8fa1216ee8",
        "mode": "chat", 
        "character": "None",
        "instruction_template": "None",
        "your_name": "DaDa",
        "regenerate": "False",
        "_continue": "False",
        "stop_at_newline": "False",
        "chat_prompt_size": 2048,
        "chat_generation_attempts": 1,
        "chat-instruct_command": "Continue the chat dialogue below. Write a single reply for the character <|character|>.\n\n<|prompt|>",
        "max_new_tokens": 250,
        "do_sample": "True",
        "temperature": 0.7,
        "top_p": 0.1,
        "typical_p": 1,
        "epsilon_cutoff": 0, 
        "eta_cutoff": 0,
        "tfs": 1,
        "top_a": 0,
        "repetition_penalty": 1.18,
        "top_k": 40,
        "min_length": 0,
        "no_repeat_ngram_size": 0,
        "num_beams": 1,
        "penalty_alpha": 0,
        "length_penalty": 1,
        "early_stopping": "False",
        "mirostat_mode": 0,
        "mirostat_tau": 5,
        "mirostat_eta": 0.1,
        "seed": -1,
        "add_bos_token": "True",
        "truncation_length": 2048,
        "ban_eos_token": "False",
        "skip_special_tokens": "True"
}

but it response : below error message 

Exception occurred during processing of request from ('172.22.0.1', 57434)

Traceback (most recent call last):

  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread

    self.finish_request(request, client_address)

  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request

    self.RequestHandlerClass(request, client_address, self)

  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/app/extensions/api/blocking_api.py", line 84, in do_POST
    for a in generator:
  File "/app/modules/chat.py", line 340, in generate_chat_reply
    if (len(history['visible']) == 1 and not history['visible'][0][0]) or len(history['internal']) == 0:
TypeError: string indices must be integers.  

Can u let me know a example to make a correct request ? 

Many thanks

**Comment by HyeongminMoon** [comment]
@eu09 My apologies, this implementation is about webui, I haven't tested the api. I'll check it later.

**Comment by eu09** [comment]
But when I use following content in the json body , so please let me know how can I make the request by restful for asking a question and how to continue the dialog . 

{
        "user_input": "hello how are u ",
        "history": {"visible": "",
                    "internal": ""
        },   
        "mode": "chat", 
        "character": "None",
        "instruction_template": "None",
        "your_name": "DaDa",
        "regenerate": "False",
        "_continue": "False",
        "stop_at_newline": "False",
        "chat_prompt_size": 2048,
        "chat_generation_attempts": 1,
        "chat-instruct_command": "Continue the chat dialogue below. Write a single reply for the character <|character|>.\n\n<|prompt|>",
        "max_new_tokens": 250,
        "do_sample": "True",
        "temperature": 0.7,
        "top_p": 0.1,
        "typical_p": 1,
        "epsilon_cutoff": 0, 
        "eta_cutoff": 0,
        "tfs": 1,
        "top_a": 0,
        "repetition_penalty": 1.18,
        "top_k": 40,
        "min_length": 0,
        "no_repeat_ngram_size": 0,
        "num_beams": 1,
        "penalty_alpha": 0,
        "length_penalty": 1,
        "early_stopping": "False",
        "mirostat_mode": 0,
        "mirostat_tau": 5,
        "mirostat_eta": 0.1,
        "seed": -1,
        "add_bos_token": "True",
        "truncation_length": 2048,
        "ban_eos_token": "False",
        "skip_special_tokens": "True"
}

Then it return :  200 as following response 
{
    "results": [
        {
            "history": {
                "visible": "",
                "internal": ""
            }
        }
    ]

**Comment by HyeongminMoon** [comment]
As I've written above, I added two variables multi_history, multi_stop_everything. Please refer to modules/shared.py & chat.py

I changed the methods in module/chat.py by adding the uuid parameter, so we need to modify the api extension script the same way.

I don't have a plan to support multi-user mode for api extension, but it would be appreciated if you would contribute to it:)

**Comment by oobabooga** [comment]
Multi-user support has been added here without uuid, by just converting shared.history into a gr.State variable that is bound to a single session https://github.com/oobabooga/text-generation-webui/pull/2991

By adding the --multi-user flag, the session/chat histories are not automatically saved, so it should work for multiple users. Not safe for using in the open though since users can load and unload models, restart the ui, change command-line flags, etc.

**Comment by Vishal-Raghav** [comment]
Hi @oobabooga @HyeongminMoon ,

When I run the below command I get the following error. Is the multi chat support feature no longer available?

C:\User\Desktop\Copilot\text-generation-webui>**python server.py --chat --multi_user [--multi_cnt 10]**
usage: server.py [-h] [--notebook] [--chat] [--character CHARACTER] [--model MODEL] [--lora LORA [LORA ...]]
                 [--model-dir MODEL_DIR] [--lora-dir LORA_DIR] [--model-menu] [--no-stream] [--settings SETTINGS]
                 [--extensions EXTENSIONS [EXTENSIONS ...]] [--verbose] [--loader LOADER] [--cpu] [--auto-devices]
                 [--gpu-memory GPU_MEMORY [GPU_MEMORY ...]] [--cpu-memory CPU_MEMORY] [--disk]
                 [--disk-cache-dir DISK_CACHE_DIR] [--load-in-8bit] [--bf16] [--no-cache] [--xformers]
                 [--sdp-attention] [--trust-remote-code] [--load-in-4bit] [--compute_dtype COMPUTE_DTYPE]
                 [--quant_type QUANT_TYPE] [--use_double_quant] [--threads THREADS] [--n_batch N_BATCH] [--no-mmap]
                 [--mlock] [--cache-capacity CACHE_CAPACITY] [--n-gpu-layers N_GPU_LAYERS] [--n_ctx N_CTX]
                 [--llama_cpp_seed LLAMA_CPP_SEED] [--wbits WBITS] [--model_type MODEL_TYPE] [--groupsize GROUPSIZE]
                 [--pre_layer PRE_LAYER [PRE_LAYER ...]] [--checkpoint CHECKPOINT] [--monkey-patch] [--quant_attn]
                 [--warmup_autotune] [--fused_mlp] [--gptq-for-llama] [--autogptq] [--triton]
                 [--no_inject_fused_attention] [--no_inject_fused_mlp] [--no_use_cuda_fp16] [--desc_act]
                 [--gpu-split GPU_SPLIT] [--max_seq_len MAX_SEQ_LEN] [--compress_pos_emb COMPRESS_POS_EMB] [--flexgen]
                 [--percent PERCENT [PERCENT ...]] [--compress-weight] [--pin-weight [PIN_WEIGHT]] [--deepspeed]
                 [--nvme-offload-dir NVME_OFFLOAD_DIR] [--local_rank LOCAL_RANK] [--rwkv-strategy RWKV_STRATEGY]
                 [--rwkv-cuda-on] [--listen] [--listen-host LISTEN_HOST] [--listen-port LISTEN_PORT] [--share]
                 [--auto-launch] [--gradio-auth GRADIO_AUTH] [--gradio-auth-path GRADIO_AUTH_PATH] [--api]
                 [--api-blocking-port API_BLOCKING_PORT] [--api-streaming-port API_STREAMING_PORT] [--public-api]
                 [--multimodal-pipeline MULTIMODAL_PIPELINE]
**server.py: error: unrecognized arguments: --multi_user [--multi_cnt 10]**

**Comment by HyeongminMoon** [comment]
@Vishal-Raghav As ooba mentioned, now multi user supports is added to main branch. Refer to #2991, now you can only add `--multi-user` instead of `--multi_user [--multi_cnt 10]`. Make sure you're using the latest version too. `git pull` command would be helpful.

**Pull request closed without merging**
