### PR TITLE
Intel Gpu support initialization

### PR DESCRIPTION
**Pull request by abhilash1910**
From thread #1575 
WIP (Draft mode) 

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by oobabooga** [comment]
Looking very good!

**Comment by abhilash1910** [comment]
Added preliminary support  , certain ISAs related to AMX are to be added in llama cpp (hence I have not added those yet).  Can be tested on Intel Arc devices , now . 
cc @oobabooga

**Comment by oobabooga** [comment]
@abhilash1910 I have reviewed the changes and they look good. The level of detail in this PR is extremely impressive -- you have accelerated something that would have taken me several months or indefinitely to do, given that I do not have an Intel Arc GPU and they are not readily available on GPU rental platforms.

I think that the best way to get it tested is to get it merged and let users test it on main, so let's do that.

**Comment by naptastic** [comment]
I have an A770 and have not succeeded in using this so far. The problems are all environmental. @abhilash1910 how do you start an environment to have all the right Intel libraries and modules? I'm stumped; it seems like all roads lead to an ABI mismatch. Are you using Conda or something else?

**Comment by fractal-fumbler** [comment]
@naptastic, try ```source /opt/intel/oneapi/setvars.sh```

**Comment by naptastic** [comment]
Ok, that got me most of the way there. It was still necessary to do `conda activate pytorch-gpu` and then install dependencies. (gradio, markdown, transformers, torch_grammar, accelerate, datasets, peft). It's still not working due to a problem with the gradio interface but it's not related to this PR. (I will still update this post with the complete answer once I have it though.)

**Comment by fractal-fumbler** [comment]
@naptastic, suggest continue here 
https://github.com/oobabooga/text-generation-webui/issues/3761#issuecomment-1807216178

**Pull request merged**
