### PR TITLE
Added "api-character-example-stream.py"

### PR DESCRIPTION
**Pull request by MikoAL**
I think a lot of people would like to have this feature?
So I modified a bit of my spaghetti code, hoping it would be semi-readable, and hope that I can be of use.

### CODE REVIEW

**Comment by SleepyZzed** [comment]
I seem to get an error trying to run this:

  asyncio.run(print_response_stream(prompt))
TypeError: print_response_stream() missing 1 required positional argument: 'stopping_strings'

**Comment by magokeanu** [comment]
> I seem to get an error trying to run this:
> 
> asyncio.run(print_response_stream(prompt)) TypeError: print_response_stream() missing 1 required positional argument: 'stopping_strings'

Hi Slepyzzed, I had the same error, as you can see in the function print_response_stream() you need two arguments, so instead of using asyncio.run(print_response_stream(prompt)) as it is in the example I used asyncio.run(print_response_stream(prompt, "")), where "" is just to test it xd, I guess "\n" would be a good option.

**Comment by magokeanu** [comment]
I have a problem trying to execute the run function:

RuntimeError: asyncio.run() cannot be called from a running event loop

I need to say that I just downloaded the file and used it in the main oobabooga branch xd, Someone with the same error? Meanwhile I will try to fix it.

**Comment by SleepyZzed** [comment]
> I have a problem trying to execute the run function:
> 
> RuntimeError: asyncio.run() cannot be called from a running event loop
> 
> I need to say that I just downloaded the file and used it in the main oobabooga branch xd, Someone with the same error? Meanwhile I will try to fix it.

did you ever get character api working? I've been struggling to make it work 😅

**Pull request closed without merging**
