### PR TITLE
Add launch.py to remember args history and check environments

### PR DESCRIPTION
**Pull request by Orion-zhen**
# Brief
I find that every time I start the `server.py`, I should type many arguments to load model and extensions even though I loaded them last time.

So I added a `launch.py` to record arguments used last time into `history.json` in order to avoid retyping.

Noticing that the `launch.py` of [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) can perform environment check, I added similar functions to my `launch.py`.

# Changes
I added two arguments `--check` and `--no-history` to `modules/shared.py`, `parser` in line102.

Argument `--check` can automacitally check for updates, pulling down to your device. And check your python environments and install missing python modules.

Argument `--no-history` means you want to lauch server.py without any arguments.

`python launch.py` without arguments will load arguments used last time.

`python launch.py --some-args` eqauls to `python server.py --some-args`.

Everytime you run `launch.py`, it will generate a message like this:
```shell
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Version: <none>
Commit hash: 0a0adb328b25e1dfc3f244724f56c97abd806f44
```

# BTW
This is my first time to create a pull request. I'm kind of nervous.

At first, I wanted to write an extension manage page like sd-webui, where you can search extensions you want to install, check those you want to load, and they will be loaded next time. But due to my lack of experience, I've tried my best but only understood a little about text-generation-webui and sd-webui. So I just worte such a poor script. Please forgive me if any bug is found.

Thank you for reading this message. I'm sorry if I bothered you.

### CODE REVIEW

**Comment by Ph0rk0z** [comment]
For me, I have been using the web based UI to avoid typing so many arguments. The main one that I'm stuck using now is the pre-layer. It makes it so I have to type out everything including model name.

I get a bit wary of anything that checks my environment or does updates though. Sometimes pip install -U can install CPU torch or requirements.txt disagrees with what I'm using and tries to downgrade me.

I sort of get annoyed at that part of automatic111.. it also started to d/l some SD model on me because of course new users want a model right? No, I just re-installed and plan on symbolically linking my 40 gigs of them once everything is set up. Did not need the multi gig pytorch surprise before I could proceed.

**Comment by Orion-zhen** [comment]
> For me, I have been using the web based UI to avoid typing so many arguments. The main one that I'm stuck using now is the pre-layer. It makes it so I have to type out everything including model name.
> 
> I get a bit wary of anything that checks my environment or does updates though. Sometimes pip install -U can install CPU torch or requirements.txt disagrees with what I'm using and tries to downgrade me.
> 
> I sort of get annoyed at that part of automatic111.. it also started to d/l some SD model on me because of course new users want a model right? No, I just re-installed and plan on symbolically linking my 40 gigs of them once everything is set up. Did not need the multi gig pytorch surprise before I could proceed.

Thank you for your comment.

As I said, my motivation is to write a extension manage page, for example, to load models and extensions without reloading webui, noticing that if you closes the text-generation-webui process, next time you start it, you might have to waiting until webui loads default language model, you checking models and extensions you want to load, and restart the webui. I discover this process kind of slow. Shorten that process is my intention.

BTW, may I ask how to achieve the effect that webui can remember the state of last time after closing webui process?

As for checking environment, `launch.py` does not aggressively changes your environment. Without `--check`, it just output some version messages without changing anything on environments.

This pr seems to be unhelpful, should I delete it?

**Comment by Ph0rk0z** [comment]
Nah, don't delete your work. Leave it up. This is just my opinion.

You may want to turn off autoloading if you are having it load a model from the web by default. I was not a big fan of that either so switch it off.

**Comment by Orion-zhen** [comment]
> Nah, don't delete your work. Leave it up. This is just my opinion.
> 
> You may want to turn off autoloading if you are having it load a model from the web by default. I was not a big fan of that either so switch it off.

Thank you. It's a precious experience to join the community for me.

Maybe I should squeeze some time in summer vacation to dive into gradio and llms.

Goodnight ヾ(^▽^*)))

**Comment by Orion-zhen** [comment]
Well, it seems that I did something wrong. I made a pr based on my main branch, and any change to this branch will sync to the pr. It's a mistake due to my lack of expreince. Given that this pr is unnecessary, and I shouldn't post commits irrelevant to the topic, I should close this pr. Next time I will create a new branch •﹏•

**Pull request closed without merging**
