### PR TITLE
Apply the settings for extensions after import, but before setup()

### PR DESCRIPTION
**Pull request by da3dsoul**
I had an issue where there wasn't an easy way to init an extension based on settings. Before, you could theoretically do it by performing that logic in ui(), but setup() should have the settings loaded, imo

### CODE REVIEW

**Comment by oobabooga** [comment]
That definitely makes sense. I have merged the main branch which had some changes to the extensions framework since your PR was submitted. Everything seems to be working, but please let me know if you encounter any issues.

**Comment by LaaZa** [comment]
I think this broke loading settings for LLaVA. Do I have to change the settings format somehow?

**Comment by oobabooga** [comment]
No, the format should be the same

**Comment by LaaZa** [comment]
Stopped loading the settings though.

**Comment by oobabooga** [comment]
Can you check if this fixed it? https://github.com/oobabooga/text-generation-webui/commit/da812600f49309cd7090464d7ffcfa1246d3a309

**Comment by LaaZa** [comment]
Yes, fixed.

**Pull request merged**
