### PR TITLE
Add q-cache 6 and 8 support for Exllamav2

### PR DESCRIPTION
**Pull request by randoentity**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/oobabooga/text-generation-webui/wiki/Contributing-guidelines).

### CODE REVIEW

**Comment by Nicoolodion** [comment]
Hm seems like oobabooga has abandoned the webui almost completly. Changes get ignored even tho the version of exllama we are using is ancient.
Seems like the end of all of this is near :/

**Comment by ZedOud** [comment]
Some of the names and references have changes, but otherwise this works.

**Comment by randoentity** [comment]
@ZedOud thanks for testing. Can you propose changes for the names and references so I can remain lazy?

**Comment by Originalimoc** [comment]
```
shared.gradio['cache_4bit'] = gr.Checkbox(label="cache_4bit", value=shared.args.cache_8bit, info='Use 4-bit (FP4) cache to save VRAM.')
```
Are you sure this is correct?

**Comment by Originalimoc** [comment]
FYI 7B FP16&8.0BPW Qwen2.5 with --cache_4bit is just outputting garbage..., while FP16 full cache is fine:
```
You're right; I apologize for missing that step.

So, to get the the0.00000766531795656 for the input/token outputтокen and $0.0.38155679 for the outputтокenn.

Thas give $7.66 for the input/токen and $8.65 for the outputтокen million.
system
1,000,000,00 * 0,00000002531795656 = 2,666.285566653388 \n 1,000,000,00 * 0,0000008657957956 = 7,657.57839935568

system
1,000,000,000 * 0,00000002531795666 = 2,5333899938757998 \n 1,000,,,000,00 * 0,0000057958332054 = 7,6568326602265769

system
2,653,333,333 \n 7,65,832,266

71828394
971556
system
2,000,000,000 * 0,000007565317956 = 1,155755
...or...
Apologies for the
-END OF-sn

_solution6.686_7888888864
actuallySystem
Instructionsionary\tStep	StepB	StepStepStepStepStepStepStepStpeStepStepStepStpeStepStepStepStepStepStepStepStepStepStepStepStepStepStepStepStepStepStepStepStpepepSteppoepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepepe
```

Fine:
```
You're right. I apologize for the oversight. Let's multiply the prices by 1,000,000.

The price per million tokens for input/prompt is:
0.00000253846153846
×
1
,
000
,
000
=
2.53846153846

The price per million tokens for completion is:
0.00001
×
1
,
000
,
000
=
10

So, the final answers are:

The price for the input/prompt tokens is 2.538 million.
The price for the completion tokens is 10 million.
Therefore, the total price for 1 million tokens is 2.538 and 10.
...or...
You're right. I apologize for the oversight. Let's multiply the values by 1,000,000:

x = 0.00000253846153846 * 1,000,000 = 2.53846153846

y = 0.00001 * 1,000,000 = 10

So, the cost for 1 million tokens is:

Input/prompt: $2.53846153846 ≈ $2.54

Completion: $10

The final answer is:
The cost for 1 million tokens is $2.54 for the input/prompt and $10 for the completion.

If you have any more questions or need further clarification, feel free to ask!
```
Which is good enough for a 7B

**Comment by oobabooga** [comment]
I'm inclined to https://github.com/oobabooga/text-generation-webui/pull/6561 in favor of this PR. Reviews there are welcome.

**Comment by oobabooga** [comment]
Closing this one in favor of https://github.com/oobabooga/text-generation-webui/pull/6561. Thanks for the PR @randoentity and sorry for not having reviewed earlier!

**Pull request closed without merging**
