### PR TITLE
Add support low vram mode on llama.cpp module

### PR DESCRIPTION
**Pull request by gabriel-pena**
I decided to add support for lowvram mode to llama.cpp module because I had a lot of problems with high vram usage and this will help a lot of people who have low vram

### CODE REVIEW

**Comment by oobabooga** [comment]
What does this do?

**Comment by Dampfinchen** [comment]
> What does this do?

Results in KV Cache to get moved back into RAM and thus, freeing VRAM. In my testing with split layers I didn't notice much performance regression but indeed a lower VRAM usage, allowing me to use more layers on the GPU and increasing performance. So yeah its quite nice.

**Comment by oobabooga** [comment]
Thanks for the clarification @Dampfinchen

**Comment by berkut1** [comment]
@gabriel-pena is it really helps? I tested that mode 2 weeks ago on my RTX 2080 8 GB with 13b models, and notice no effect, only -5% of performance.

**Comment by gabriel-pena** [comment]
> @gabriel-pena is it really helps? I tested that mode 2 weeks ago on my RTX 2080 8 GB with 13b models, and notice no effect, only -5% of performance.

Yes, this mode helps a lot.  couldn't run ggml models above 7b q4_ks well on my GTX 1660ti, always had vram overflow.  and using low vram mode I can run models up to type 7b q5_km with little performance loss.  Using low vram mode in a model like 7b q5_km I can generate up to 13 tokens per second

**Comment by berkut1** [comment]
@gabriel-pena  Hmm... ok, maybe this mode is effective for a GPU with less than 8 GB of VRAM. On my video card, it's more beneficial to reduce the GPU layers to fit in VRAM as much as possible..

**Pull request merged**
