### PR TITLE
bump gradio to 3.28

### PR DESCRIPTION
**Pull request by catalpaaa**
importent changes:
1. Fix bug where port was not reused if the demo was closed and then re-launched by [@freddyaboulton](https://github.com/freddyaboulton) in [PR 3896](https://github.com/gradio-app/gradio/pull/3959)
2. Fix issue where requesting for a non-existing file would trigger a 500 error by [@micky2be](https://github.com/micky2be) in [PR 3895](https://github.com/gradio-app/gradio/pull/3895).
3. Fix bugs with abspath about symlinks, and unresolvable path on Windows by [@micky2be](https://github.com/micky2be) in [PR 3895](https://github.com/gradio-app/gradio/pull/3895).

this fixes:

- #1632
- #1407 
- https://github.com/gradio-app/gradio/issues/3675
- and more similar issues

### CODE REVIEW

**Comment by Malrama** [comment]
3.28.1 just got released too.
Things moving so fast nowadays

**Comment by DavG25** [comment]
Updating Gradio to 3.28 also closes https://github.com/oobabooga/text-generation-webui/pull/1290

**Comment by catalpaaa** [comment]
> 3.28.1 just got released too. Things moving so fast nowadays

3.28.1 fixes broken dropdown in 3.28, good stuff

**Comment by oobabooga** [comment]
Updated here https://github.com/oobabooga/text-generation-webui/commit/d016c3864051ad8c15c345efc9098957345c865f

**Pull request closed without merging**
